'use strict';

/**
 * Guesses what REL the user wants to disassemble given the string REL
 * identifier they provided.
 */

const Fuse = require('fuse.js');
const RecognizedError = require('./RecognizedError');

// prettier-ignore
const relsMap = {
  f_pc_profile_lst: { id: 0x0001, index: '', readable: 'F - PC - Profile - List', category: 'mmem', },
  d_a_andsw: { id: 0x0002, index: '0230', readable: 'And Switch', category: 'mmem', },
  d_a_bg: { id: 0x0003, index: '02dc', readable: 'Background - Obj', category: 'mmem', },
  d_a_bg_obj: { id: 0x0004, index: '02de', readable: 'Background', category: 'mmem', },
  d_a_dmidna: { id: 0x0005, index: '02d8', readable: 'Dying Midna', category: 'mmem', },
  d_a_door_dbdoor00: { id: 0x0006, index: '0227', readable: 'Door - Double Door 00', category: 'mmem', },
  d_a_door_knob00: { id: 0x0007, index: '0226', readable: 'Door - Knob 00', category: 'mmem', },
  d_a_door_shutter: { id: 0x0008, index: '00e8', readable: 'Door - Shutter', category: 'mmem', },
  d_a_door_spiral: { id: 0x0009, index: '022d', readable: 'Door - Spiral', category: 'mmem', },
  d_a_dshutter: { id: 0x000a, index: '022c', readable: 'D Shutter', category: 'mmem', },
  d_a_ep: { id: 0x000b, index: '0105', readable: 'Ep', category: 'mmem', },
  d_a_hitobj: { id: 0x000c, index: '0104', readable: 'Hit Object', category: 'mmem', },
  d_a_kytag00: { id: 0x000d, index: '02aa', readable: 'K Twilight Tag 00', category: 'mmem', },
  d_a_kytag04: { id: 0x000e, index: '02ae', readable: 'K Twilight Tag 04', category: 'mmem', },
  d_a_kytag17: { id: 0x000f, index: '02bb', readable: 'K Twilight Tag 17', category: 'mmem', },
  d_a_obj_brakeeff: { id: 0x0010, index: '0025', readable: 'Obj - Brake Effect', category: 'mmem', },
  d_a_obj_burnbox: { id: 0x0011, index: '00dc', readable: 'Obj - Burn Box', category: 'mmem', },
  d_a_obj_carry: { id: 0x0012, index: '02fc', readable: 'Obj - Carry', category: 'mmem', },
  d_a_obj_ito: { id: 0x0013, index: '00f0', readable: 'Obj - String', category: 'mmem', },
  d_a_obj_movebox: { id: 0x0014, index: '001d', readable: 'Obj - Move Box', category: 'mmem', },
  d_a_obj_swpush: { id: 0x0015, index: '0016', readable: 'Obj - Switch Push', category: 'mmem', },
  d_a_obj_timer: { id: 0x0016, index: '030b', readable: 'Obj - Timer', category: 'mmem', },
  d_a_path_line: { id: 0x0017, index: '0309', readable: 'Path - Line', category: 'mmem', },
  d_a_scene_exit: { id: 0x0018, index: '030c', readable: 'Scene - Exit', category: 'mmem', },
  d_a_set_bgobj: { id: 0x0019, index: '02dd', readable: 'Set - Background Object', category: 'mmem', },
  d_a_swhit0: { id: 0x001a, index: '02e7', readable: 'Switch Hit 0', category: 'mmem', },
  d_a_tag_allmato: { id: 0x001b, index: '030a', readable: 'Tag - All Targets', category: 'mmem', },
  d_a_tag_camera: { id: 0x001c, index: '02cf', readable: 'Tag - Camera', category: 'mmem', },
  d_a_tag_chkpoint: { id: 0x001d, index: '02d0', readable: 'Tag - Checkpoint', category: 'mmem', },
  d_a_tag_event: { id: 0x001e, index: '02d1', readable: 'Tag - Event', category: 'mmem', },
  d_a_tag_evt: { id: 0x001f, index: '02d2', readable: 'Tag - Event', category: 'mmem', },
  d_a_tag_evtarea: { id: 0x0020, index: '02e9', readable: 'Tag - Event Area', category: 'mmem', },
  d_a_tag_evtmsg: { id: 0x0021, index: '02ea', readable: 'Tag - Event Message', category: '', },
  d_a_tag_howl: { id: 0x0022, index: '02d4', readable: 'Tag - Howl', category: 'mmem', },
  d_a_tag_kmsg: { id: 0x0023, index: '02eb', readable: 'Tag - K Message', category: 'mmem', },
  d_a_tag_lantern: { id: 0x0024, index: '02d6', readable: 'Tag - Lantern', category: 'mmem', },
  d_a_tag_mist: { id: 0x0025, index: '02d7', readable: 'Tag - Mist', category: 'mmem', },
  d_a_tag_msg: { id: 0x0026, index: '02d5', readable: 'Tag - Message', category: 'mmem', },
  d_a_tag_push: { id: 0x0027, index: '02ec', readable: 'Tag - Push', category: 'mmem', },
  d_a_tag_telop: { id: 0x0028, index: '02d3', readable: 'Tag - Telop', category: 'mmem', },
  d_a_tbox: { id: 0x0029, index: '00fb', readable: 'Treasure Chest', category: 'mmem', },
  d_a_tbox2: { id: 0x002a, index: '00fc', readable: 'Treasure Chest 2', category: 'mmem', },
  d_a_vrbox: { id: 0x002b, index: '02da', readable: 'VR Box', category: 'mmem', },
  d_a_vrbox2: { id: 0x002c, index: '02db', readable: 'VR Box 2', category: 'mmem', },
  d_a_arrow: { id: 0x002d, index: '0308', readable: 'Arrow', category: 'mmem', },
  d_a_boomerang: { id: 0x002e, index: '00fe', readable: 'Boomerang', category: 'mmem', },
  d_a_crod: { id: 0x002f, index: '02f4', readable: 'Copy Rod', category: 'mmem', },
  d_a_demo00: { id: 0x0030, index: '02ce', readable: 'Cutscene 00', category: 'mmem', },
  d_a_disappear: { id: 0x0031, index: '0139', readable: 'Disappear', category: 'mmem', },
  d_a_mg_rod: { id: 0x0032, index: '02e4', readable: 'Minigame - Rod', category: 'mmem', },
  d_a_midna: { id: 0x0033, index: '00ff', readable: 'Midna', category: 'mmem', },
  d_a_nbomb: { id: 0x0034, index: '0221', readable: 'Normal Bomb', category: 'mmem', },
  d_a_obj_life_container: { id: 0x0035, index: '021b', readable: 'Obj - Life - Container', category: 'mmem', },
  d_a_obj_yousei: { id: 0x0036, index: '013f', readable: 'Obj - Fairy', category: 'mmem', },
  d_a_spinner: { id: 0x0037, index: '00f2', readable: 'Spinner', category: 'mmem', },
  d_a_suspend: { id: 0x0038, index: '030f', readable: 'Suspend', category: 'mmem', },
  d_a_tag_attention: { id: 0x0039, index: '015a', readable: 'Tag - Attention', category: 'mmem', },
  d_a_alldie: { id: 0x003a, index: '0014', readable: 'All Die', category: 'amem', },
  d_a_andsw2: { id: 0x003b, index: '0231', readable: 'And Switch 2', category: 'amem', },
  d_a_bd: { id: 0x003c, index: '0300', readable: 'Bird', category: 'amem', },
  d_a_canoe: { id: 0x003d, index: '00ed', readable: 'Canoe', category: 'amem', },
  d_a_cstaf: { id: 0x003e, index: '00bb', readable: 'Copy Statue F', category: 'amem', },
  d_a_demo_item: { id: 0x003f, index: '021d', readable: 'Cutscene - Item', category: 'amem', },
  d_a_door_bossl1: { id: 0x0040, index: '0229', readable: 'Door - Boss (Level 1)', category: 'amem', },
  d_a_e_dn: { id: 0x0041, index: '01b3', readable: 'Enemy - Dinolfos', category: 'amem', },
  d_a_e_fm: { id: 0x0042, index: '01d7', readable: 'Enemy - Fire Man', category: 'amem', },
  d_a_e_ga: { id: 0x0043, index: '01c7', readable: 'Enemy - Moth', category: 'amem', },
  d_a_e_hb: { id: 0x0044, index: '01c9', readable: 'Enemy - Serpent Baba', category: 'amem', },
  d_a_e_nest: { id: 0x0045, index: '01e8', readable: 'Enemy - Nest', category: 'amem', },
  d_a_e_rd: { id: 0x0046, index: '01d4', readable: 'Enemy - Rider', category: 'amem', },
  d_a_econt: { id: 0x0047, index: '02e3', readable: 'Encounter', category: 'amem', },
  d_a_fr: { id: 0x0048, index: '02e2', readable: 'Frog', category: 'amem', },
  d_a_grass: { id: 0x0049, index: '0310', readable: 'Grass', category: 'amem', },
  d_a_kytag05: { id: 0x004a, index: '02af', readable: 'K Twilight Tag 05', category: 'amem', },
  d_a_kytag10: { id: 0x004b, index: '02b4', readable: 'K Twilight Tag 10', category: 'amem', },
  d_a_kytag11: { id: 0x004c, index: '02b5', readable: 'K Twilight Tag 11', category: 'amem', },
  d_a_kytag14: { id: 0x004d, index: '02b8', readable: 'K Twilight Tag 14', category: 'amem', },
  d_a_mg_fish: { id: 0x004e, index: '0136', readable: 'Minigame - Fish', category: 'amem', },
  d_a_npc_besu: { id: 0x004f, index: '0245', readable: 'NPC - Beth', category: 'amem', },
  d_a_npc_fairy_seirei: { id: 0x0050, index: '0252', readable: 'NPC - Fairy - Spirit', category: 'amem', },
  d_a_npc_fish: { id: 0x0051, index: '0135', readable: 'NPC - Fish', category: 'amem', },
  d_a_npc_henna: { id: 0x0052, index: '0255', readable: 'NPC - Hena', category: 'amem', },
  d_a_npc_kakashi: { id: 0x0053, index: '0241', readable: 'NPC - Scarecrow', category: 'amem', },
  d_a_npc_kkri: { id: 0x0054, index: '0259', readable: 'NPC - Coro', category: 'amem', },
  d_a_npc_kolin: { id: 0x0055, index: '025d', readable: 'NPC - Colin', category: 'amem', },
  d_a_npc_maro: { id: 0x0056, index: '0260', readable: 'NPC - Malo', category: 'amem', },
  d_a_npc_taro: { id: 0x0057, index: '026e', readable: 'NPC - Talo', category: 'amem', },
  d_a_npc_tkj: { id: 0x0058, index: '0274', readable: 'NPC - Sky Dweller Jr.', category: 'amem', },
  d_a_obj_bhashi: { id: 0x0059, index: '006c', readable: 'Object - Boss Pillar', category: 'amem', },
  d_a_obj_bkdoor: { id: 0x005a, index: '0062', readable: 'Object - Ranch Door', category: 'amem', },
  d_a_obj_bosswarp: { id: 0x005b, index: '0163', readable: 'Object - Boss Warp', category: 'amem', },
  d_a_obj_cboard: { id: 0x005c, index: '0063', readable: 'Object - Clear Board', category: 'amem', },
  d_a_obj_digplace: { id: 0x005d, index: '0053', readable: 'Object - Dig Place', category: 'amem', },
  d_a_obj_eff: { id: 0x005e, index: '0301', readable: 'Object - Effect', category: 'amem', },
  d_a_obj_fmobj: { id: 0x005f, index: '0026', readable: 'Object - Fire Man Object', category: 'amem', },
  d_a_obj_gptaru: { id: 0x0060, index: '016b', readable: 'Object - Gunpowder Barrel', category: 'amem', },
  d_a_obj_hhashi: { id: 0x0061, index: '006b', readable: 'Object - H Pillar', category: 'amem', },
  d_a_obj_kanban2: { id: 0x0062, index: '011b', readable: 'Object - Sign 2', category: 'amem', },
  d_a_obj_kbacket: { id: 0x0063, index: '02f6', readable: 'Object - K Bucket', category: 'amem', },
  d_a_obj_kgate: { id: 0x0064, index: '0080', readable: 'Object - K Gate', category: 'amem', },
  d_a_obj_klift00: { id: 0x0065, index: '00d1', readable: 'Object - K Lift 00', category: 'amem', },
  d_a_obj_ktonfire: { id: 0x0066, index: '0168', readable: 'Object - Lantern On Fire', category: 'amem', },
  d_a_obj_ladder: { id: 0x0067, index: '0024', readable: 'Object - Ladder', category: 'amem', },
  d_a_obj_lv2candle: { id: 0x0068, index: '0049', readable: 'Object - Level 2 Candle', category: 'amem', },
  d_a_obj_magne_arm: { id: 0x0069, index: '00c6', readable: 'Object - Magnet - Arm', category: 'amem', },
  d_a_obj_metalbox: { id: 0x006a, index: '0079', readable: 'Object - Metal Box', category: 'amem', },
  d_a_obj_mgate: { id: 0x006b, index: '0064', readable: 'Object - Forest Gate', category: 'amem', },
  d_a_obj_nameplate: { id: 0x006c, index: '0150', readable: 'Object - Nameplate', category: 'amem', },
  d_a_obj_ornament_cloth: { id: 0x006d, index: '0151', readable: 'Object - Ornament - Cloth', category: 'amem', },
  d_a_obj_rope_bridge: { id: 0x006e, index: '0085', readable: 'Object - Rope - Bridge', category: 'amem', },
  d_a_obj_swallshutter: { id: 0x006f, index: '004c', readable: 'Object - S Wall Shutter', category: 'amem', },
  d_a_obj_stick: { id: 0x0070, index: '0130', readable: 'Object - Stick', category: 'amem', },
  d_a_obj_stonemark: { id: 0x0071, index: '0171', readable: 'Object - Stone Mark', category: 'amem', },
  d_a_obj_swpropeller: { id: 0x0072, index: '005e', readable: 'Object - Switch Propeller', category: 'amem', },
  d_a_obj_swpush5: { id: 0x0073, index: '0018', readable: 'Object - Switch Push 5', category: 'amem', },
  d_a_obj_yobikusa: { id: 0x0074, index: '014d', readable: 'Object - Call Grass', category: 'amem', },
  d_a_scene_exit2: { id: 0x0075, index: '01a7', readable: 'Scene - Exit 2', category: 'amem', },
  d_a_shop_item: { id: 0x0076, index: '021e', readable: 'Shop - Item', category: 'amem', },
  d_a_sq: { id: 0x0077, index: '010a', readable: 'Squirrel', category: 'amem', },
  d_a_swc00: { id: 0x0078, index: '0225', readable: 'Switch C 00', category: 'amem', },
  d_a_tag_cstasw: { id: 0x0079, index: '0190', readable: 'Tag - Copy Statue Switch', category: 'amem', },
  d_a_tag_ajnot: { id: 0x007a, index: '00eb', readable: 'Tag - Aj Not', category: 'amem', },
  d_a_tag_attack_item: { id: 0x007b, index: '01aa', readable: 'Tag - Attack - Item', category: 'amem', },
  d_a_tag_gstart: { id: 0x007c, index: '0019', readable: 'Tag - G Start', category: 'amem', },
  d_a_tag_hinit: { id: 0x007d, index: '00e9', readable: 'Tag - Horse Initialization', category: 'amem', },
  d_a_tag_hjump: { id: 0x007e, index: '00ea', readable: 'Tag - Horse Jump', category: 'amem', },
  d_a_tag_hstop: { id: 0x007f, index: '00ec', readable: 'Tag - Horse Stop', category: 'amem', },
  d_a_tag_lv2prchk: { id: 0x0080, index: '0182', readable: 'Tag - Level 2 Pr Check', category: 'amem', },
  d_a_tag_magne: { id: 0x0081, index: '0162', readable: 'Tag - Magnet', category: 'amem', },
  d_a_tag_mhint: { id: 0x0082, index: '02c1', readable: 'Tag - Midna Hint', category: 'amem', },
  d_a_tag_mstop: { id: 0x0083, index: '02c4', readable: 'Tag - Midna Stop', category: 'amem', },
  d_a_tag_spring: { id: 0x0084, index: '01ad', readable: 'Tag - Spring', category: 'amem', },
  d_a_tag_statue_evt: { id: 0x0085, index: '01ae', readable: 'Tag - Statue - Event', category: 'amem', },
  d_a_ykgr: { id: 0x0086, index: '02bc', readable: 'Floor Gravity', category: 'amem', },
  d_a_L7demo_dr: { id: 0x0087, index: '0203', readable: 'Level 7 Cutscene - Dragon', category: 'rels', },
  d_a_L7low_dr: { id: 0x0088, index: '0204', readable: 'Level 7 Low - Dragon', category: 'rels', },
  d_a_L7op_demo_dr: { id: 0x0089, index: '0205', readable: 'Level 7 Opening - Cutscene - Dragon', category: 'rels', },
  d_a_b_bh: { id: 0x008a, index: '020b', readable: 'Boss - Baba Snake', category: 'rels', },
  d_a_b_bq: { id: 0x008b, index: '020c', readable: 'Boss - Baba Queen', category: 'rels', },
  d_a_b_dr: { id: 0x008c, index: '00f7', readable: 'Boss - Dragon', category: 'rels', },
  d_a_b_dre: { id: 0x008d, index: '0215', readable: 'Boss - Dragon E', category: 'rels', },
  d_a_b_ds: { id: 0x008e, index: '00f6', readable: 'Boss - Giant Stal', category: 'rels', },
  d_a_b_gg: { id: 0x008f, index: '0214', readable: 'Boss - Gargoyle', category: 'rels', },
  d_a_b_gm: { id: 0x0090, index: '020d', readable: 'Boss - Gohma', category: 'rels', },
  d_a_b_gnd: { id: 0x0091, index: '020e', readable: 'Boss - Ganondorf', category: 'rels', },
  d_a_b_go: { id: 0x0092, index: '020f', readable: 'Boss - Goron', category: 'rels', },
  d_a_b_gos: { id: 0x0093, index: '02f1', readable: 'Boss - Goron (Small)', category: 'rels', },
  d_a_b_mgn: { id: 0x0094, index: '0216', readable: 'Boss - Demon Ganon', category: 'rels', },
  d_a_b_ob: { id: 0x0095, index: '00f3', readable: 'Boss - Octaeel Body', category: 'rels', },
  d_a_b_oh: { id: 0x0096, index: '00d2', readable: 'Boss - Octaeel Head', category: 'rels', },
  d_a_b_oh2: { id: 0x0097, index: '0210', readable: 'Boss - Octaeel Head 2', category: 'rels', },
  d_a_b_tn: { id: 0x0098, index: '0213', readable: 'Boss - Darknut', category: 'rels', },
  d_a_b_yo: { id: 0x0099, index: '0211', readable: 'Boss - Snow Woman', category: 'rels', },
  d_a_b_yo_ice: { id: 0x009a, index: '0212', readable: 'Boss - Snow Woman - Ice', category: 'rels', },
  d_a_b_zant: { id: 0x009b, index: '00f9', readable: 'Boss - Zant', category: 'rels', },
  d_a_b_zant_magic: { id: 0x009c, index: '00fa', readable: 'Boss - Zant - Magic', category: 'rels', },
  d_a_b_zant_mobile: { id: 0x009d, index: '00f8', readable: 'Boss - Zant - Mobile', category: 'rels', },
  d_a_b_zant_sima: { id: 0x009e, index: '007d', readable: 'Boss - Zant - Island', category: 'rels', },
  d_a_balloon_2D: { id: 0x009f, index: '005a', readable: 'Balloon - 2D', category: 'rels', },
  d_a_bullet: { id: 0x00a0, index: '02e6', readable: 'Bullet', category: 'rels', },
  d_a_coach_2D: { id: 0x00a1, index: '0059', readable: 'Coach - 2D', category: 'rels', },
  d_a_coach_fire: { id: 0x00a2, index: '0058', readable: 'Coach - Fire', category: 'rels', },
  d_a_cow: { id: 0x00a3, index: '0106', readable: 'Cow', category: 'rels', },
  d_a_cstatue: { id: 0x00a4, index: '0198', readable: 'Copy Statue', category: 'rels', },
  d_a_do: { id: 0x00a5, index: '010c', readable: 'Dog', category: 'rels', },
  d_a_door_boss: { id: 0x00a6, index: '0228', readable: 'Door - Boss', category: 'rels', },
  d_a_door_bossL5: { id: 0x00a7, index: '022b', readable: 'Door - Boss Level 5', category: 'rels', },
  d_a_door_mbossL1: { id: 0x00a8, index: '022a', readable: 'Door - Miniboss Level 1', category: 'rels', },
  d_a_door_push: { id: 0x00a9, index: '00bf', readable: 'Door - Push', category: 'rels', },
  d_a_e_ai: { id: 0x00aa, index: '01af', readable: 'Enemy - Armos Stone', category: 'rels', notes: 'Armos', },
  d_a_e_arrow: { id: 0x00ab, index: '02e5', readable: 'Enemy - Arrow', category: 'rels', },
  d_a_e_ba: { id: 0x00ac, index: '01ea', readable: 'Enemy - Bat', category: 'rels', notes: 'Keese', },
  d_a_e_bee: { id: 0x00ad, index: '01ed', readable: 'Enemy - Bee', category: 'rels', notes: 'Bee', },
  d_a_e_bg: { id: 0x00ae, index: '0201', readable: 'Enemy - Bomb Fish', category: 'rels', notes: 'Bomb Fish', },
  d_a_e_bi: { id: 0x00af, index: '0304', readable: 'Enemy - Bomb Insect', category: 'rels', notes: 'Bombling', },
  d_a_e_bi_leaf: { id: 0x00b0, index: '0305', readable: 'Enemy - Bomb Insect - Leaf', category: 'rels', },
  d_a_e_bs: { id: 0x00b1, index: '01b7', readable: 'Enemy - Baby Stal', category: 'rels', notes: 'Stalkin', },
  d_a_e_bu: { id: 0x00b2, index: '01eb', readable: 'Enemy - Bubble', category: 'rels', notes: 'Bubble', },
  d_a_e_bug: { id: 0x00b3, index: '01ec', readable: 'Enemy - Bug', category: 'rels', notes: 'Poison Mite', },
  d_a_e_cr: { id: 0x00b4, index: '01c3', readable: 'Enemy - Crazy Runner', category: 'rels', notes: 'Bomskit', },
  d_a_e_cr_egg: { id: 0x00b5, index: '01c4', readable: 'Enemy - Crazy Runner - Egg', category: 'rels', },
  d_a_e_db: { id: 0x00b6, index: '01c5', readable: 'Enemy - Deku Baba', category: 'rels', },
  d_a_e_db_leaf: { id: 0x00b7, index: '01c6', readable: 'Enemy - Deku Baba - Leaf', category: 'rels', },
  d_a_e_dd: { id: 0x00b8, index: '01b2', readable: 'Enemy - Dodongo', category: 'rels', notes: 'Dodongo', },
  d_a_e_df: { id: 0x00b9, index: '01ba', readable: 'Enemy - Deku Flower', category: 'rels', notes: 'Deku Like', },
  d_a_e_dk: { id: 0x00ba, index: '0207', readable: 'Enemy - Electric Jellyfish', category: 'rels', notes: 'Bari', },
  d_a_e_dt: { id: 0x00bb, index: '0200', readable: 'Enemy - Deku Toad', category: 'rels', notes: 'Deku Toad', },
  d_a_e_fb: { id: 0x00bc, index: '01e5', readable: 'Enemy - Fire Bat', category: 'rels', notes: 'Fire Keese', },
  d_a_e_fk: { id: 0x00bd, index: '01e6', readable: 'Enemy - Fire Knight', category: 'rels', notes: 'Phantom Jouster', },
  d_a_e_fs: { id: 0x00be, index: '01d8', readable: '"Enemy - "', category: 'rels', },
  d_a_e_fz: { id: 0x00bf, index: '01de', readable: 'Enemy - Freezard', category: 'rels', },
  d_a_e_gb: { id: 0x00c0, index: '01c8', readable: 'Enemy - Giant Baba', category: 'rels', },
  d_a_e_ge: { id: 0x00c1, index: '01f2', readable: 'Enemy - Guay', category: 'rels', notes: 'Guay', },
  d_a_e_gi: { id: 0x00c2, index: '020a', readable: 'Enemy - Gibdo', category: 'rels', notes: 'Redead Knight', },
  d_a_e_gm: { id: 0x00c3, index: '01bb', readable: 'Enemy - Gohma', category: 'rels', notes: 'Baby Gohma', },
  d_a_e_gob: { id: 0x00c4, index: '01b1', readable: 'Enemy - Goron Boss', category: 'rels', notes: 'Dangoro', },
  d_a_e_gs: { id: 0x00c5, index: '01b0', readable: 'Enemy - Ghost Soldier', category: 'rels', notes: 'Ghost Soldier', },
  d_a_e_hb_leaf: { id: 0x00c6, index: '01ca', readable: 'Enemy - Serpent Baba - Leaf', category: 'rels', },
  d_a_e_hm: { id: 0x00c7, index: '01cf', readable: 'Enemy - Fire Slug', category: 'rels', notes: 'Torch Slug', },
  d_a_e_hp: { id: 0x00c8, index: '01e1', readable: 'Enemy - Generic Poe', category: 'rels', notes: 'Imp Poe', },
  d_a_e_hz: { id: 0x00c9, index: '01fc', readable: 'Enemy - Hz', category: 'rels', notes: 'Tile Worm', },
  d_a_e_hzelda: { id: 0x00ca, index: '01cb', readable: 'Enemy - Possessed Zelda', category: 'rels', notes: 'Zelda (Possessed)', },
  d_a_e_is: { id: 0x00cb, index: '01ee', readable: 'Enemy - Stone Soldier', category: 'rels', notes: 'Armos Titan', },
  d_a_e_kg: { id: 0x00cc, index: '01ef', readable: 'Enemy - Child Gohma', category: 'rels', notes: 'Young Gohma', },
  d_a_e_kk: { id: 0x00cd, index: '01e0', readable: 'Enemy - Ice Knight', category: 'rels', notes: 'Chilfos', },
  d_a_e_kr: { id: 0x00ce, index: '01f0', readable: 'Enemy - Kargarok R', category: 'rels', notes: 'Kargaroc (?)', },
  d_a_e_mb: { id: 0x00cf, index: '01db', readable: 'Enemy - Miniboss Baba', category: 'rels', },
  d_a_e_md: { id: 0x00d0, index: '01bc', readable: 'Enemy - Miniboss Darknut', category: 'rels', },
  d_a_e_mf: { id: 0x00d1, index: '01b5', readable: 'Enemy - Helmetfos', category: 'rels', notes: 'Dynalfos', },
  d_a_e_mk: { id: 0x00d2, index: '01dc', readable: 'Enemy - Monkey', category: 'rels', notes: 'Ook', },
  d_a_e_mk_bo: { id: 0x00d3, index: '02ed', readable: 'Enemy - Monkey - Boomerang', category: 'rels', },
  d_a_e_mm: { id: 0x00d4, index: '01dd', readable: 'Enemy - Magnemet', category: 'rels', },
  d_a_e_mm_mt: { id: 0x00d5, index: '02ee', readable: 'Enemy - Magnemet - Helmet', category: 'rels', },
  d_a_e_ms: { id: 0x00d6, index: '01e7', readable: 'Enemy - Mouse', category: 'rels', notes: 'Rat', },
  d_a_e_nz: { id: 0x00d7, index: '01e9', readable: 'Enemy - Rat', category: 'rels', notes: 'Ghoul Rat', },
  d_a_e_oc: { id: 0x00d8, index: '01fe', readable: 'Enemy - Orc', category: 'rels', notes: 'Bokoblin', },
  d_a_e_oct_bg: { id: 0x00d9, index: '0202', readable: 'Enemy - Octaeel - Bomb Fish', category: 'rels', },
  d_a_e_ot: { id: 0x00da, index: '01ff', readable: 'Enemy - Tadpole', category: 'rels', },
  d_a_e_ph: { id: 0x00db, index: '00e4', readable: 'Enemy - Peahat', category: 'rels', notes: 'Peahat', },
  d_a_e_pm: { id: 0x00dc, index: '01d9', readable: 'Enemy - Puppet Master', category: 'rels', notes: 'Skullkid', },
  d_a_e_po: { id: 0x00dd, index: '01da', readable: 'Enemy - Poe', category: 'rels', notes: 'Poe', },
  d_a_e_pz: { id: 0x00de, index: '01e4', readable: 'Enemy - Phantom Zant', category: 'rels', notes: 'Phantom Zant', },
  d_a_e_rb: { id: 0x00df, index: '01d3', readable: 'Enemy - Leever', category: 'rels', notes: 'Leever', },
  d_a_e_rdb: { id: 0x00e0, index: '01d5', readable: 'Enemy - Rider (Boss)', category: 'rels', notes: 'King Bulblin', },
  d_a_e_rdy: { id: 0x00e1, index: '01d6', readable: 'Enemy - Rider (Shadow)', category: 'rels', notes: 'Shadow Bulblin', },
  d_a_e_s1: { id: 0x00e2, index: '01b4', readable: 'Enemy - Emissary 1', category: 'rels', notes: 'Shadow Beast', },
  d_a_e_sb: { id: 0x00e3, index: '01c1', readable: 'Enemy - Shell Blade', category: 'rels', notes: 'Shell Blade', },
  d_a_e_sf: { id: 0x00e4, index: '01b8', readable: 'Enemy - Stalfos', category: 'rels', notes: 'Stalfos', },
  d_a_e_sg: { id: 0x00e5, index: '01b6', readable: 'Enemy - Skullfish', category: 'rels', notes: 'Skullfish', },
  d_a_e_sh: { id: 0x00e6, index: '01b9', readable: 'Enemy - Stalhound', category: 'rels', notes: 'Stalhound', },
  d_a_e_sm: { id: 0x00e7, index: '01bd', readable: 'Enemy - Slime', category: 'rels', notes: 'Chu Worm', },
  d_a_e_sm2: { id: 0x00e8, index: '01be', readable: 'Enemy - Slime 2', category: 'rels', },
  d_a_e_st: { id: 0x00e9, index: '01bf', readable: 'Enemy - Skulltula', category: 'rels', notes: 'Skulltula', },
  d_a_e_st_line: { id: 0x00ea, index: '01c0', readable: 'Enemy - Skulltula - Line', category: 'rels', },
  d_a_e_sw: { id: 0x00eb, index: '01f1', readable: 'Enemy - Sand Worm', category: 'rels', notes: 'Moldorm', },
  d_a_e_th: { id: 0x00ec, index: '01c2', readable: 'Enemy - Darknut Hammer', category: 'rels', notes: 'Darknut Hammer', },
  d_a_e_th_ball: { id: 0x00ed, index: '02e8', readable: 'Enemy - Darknut Hammer - Ball', category: 'rels', },
  d_a_e_tk: { id: 0x00ee, index: '01d0', readable: 'Enemy - Tk', category: 'rels', },
  d_a_e_tk2: { id: 0x00ef, index: '01d1', readable: 'Enemy - Tk2', category: 'rels', },
  d_a_e_tk_ball: { id: 0x00f0, index: '01d2', readable: 'Enemy - Tk - Ball', category: 'rels', },
  d_a_e_tt: { id: 0x00f1, index: '0206', readable: 'Enemy - Tektite', category: 'rels', notes: 'Tektite', },
  d_a_e_vt: { id: 0x00f2, index: '0208', readable: 'Enemy - Vt', category: 'rels', },
  d_a_e_warpappear: { id: 0x00f3, index: '0217', readable: 'Enemy - Warp Appear', category: 'rels', },
  d_a_e_wb: { id: 0x00f4, index: '00ef', readable: 'Enemy - Wild Boar', category: 'rels', notes: 'Bullbo', },
  d_a_e_ws: { id: 0x00f5, index: '01fd', readable: 'Enemy - Wall Skulltula', category: 'rels', notes: 'Skullwalltula', },
  d_a_e_ww: { id: 0x00f6, index: '0209', readable: 'Enemy - White Wolfos', category: 'rels', notes: 'White Wolfos', },
  d_a_e_yc: { id: 0x00f7, index: '00f5', readable: 'Enemy - Shadow Carrier', category: 'rels', notes: 'Twilit Carrier Kargarok', },
  d_a_e_yd: { id: 0x00f8, index: '01cc', readable: 'Enemy - Shadow Baba', category: 'rels', },
  d_a_e_yd_leaf: { id: 0x00f9, index: '01ce', readable: 'Enemy - Shadow Baba - Leaf', category: 'rels', },
  d_a_e_yg: { id: 0x00fa, index: '01fb', readable: 'Enemy - Shadow Fish', category: 'rels', notes: 'Shadow Vermin', },
  d_a_e_yh: { id: 0x00fb, index: '01cd', readable: 'Enemy - Shadow Serpent', category: 'rels', },
  d_a_e_yk: { id: 0x00fc, index: '01f9', readable: 'Enemy - Shadow Keese', category: 'rels', notes: 'Shadow Keese', },
  d_a_e_ym: { id: 0x00fd, index: '01f4', readable: 'Enemy - Shadow Insect', category: 'rels', notes: 'Shadow Insect', },
  d_a_e_ym_tag: { id: 0x00fe, index: '01f5', readable: 'Enemy - Shadow Insect - Tag', category: 'rels', },
  d_a_e_ymb: { id: 0x00ff, index: '01f6', readable: 'Enemy - Shadow Insect (Bloat)', category: 'rels', notes: 'Twilit Bloat', },
  d_a_e_yr: { id: 0x0100, index: '01fa', readable: 'Enemy - Shadow Roc', category: 'rels', notes: 'Shadow Kargarok', },
  d_a_e_zh: { id: 0x0101, index: '01e2', readable: 'Enemy - Zant Hand', category: 'rels', notes: "Zant's Hand", },
  d_a_e_zm: { id: 0x0102, index: '01e3', readable: 'Enemy - Zant Mask', category: 'rels', },
  d_a_e_zs: { id: 0x0103, index: '01df', readable: 'Enemy - Zombie Soldier', category: 'rels', notes: 'Staltroop', },
  d_a_formation_mng: { id: 0x0104, index: '0293', readable: 'Formation - Man (General)', category: 'rels', },
  d_a_guard_mng: { id: 0x0105, index: '0295', readable: 'Guard - Man (General)', category: 'rels', },
  d_a_horse: { id: 0x0106, index: '00ee', readable: 'Horse', category: 'rels', },
  d_a_hozelda: { id: 0x0107, index: '0224', readable: 'Horse Zelda', category: 'rels', },
  d_a_izumi_gate: { id: 0x0108, index: '0157', readable: 'Spring - Gate', category: 'rels', },
  d_a_kago: { id: 0x0109, index: '00f4', readable: 'Basket', category: 'rels', },
  d_a_kytag01: { id: 0x010a, index: '02ab', readable: 'K Twilight Tag 01', category: 'rels', },
  d_a_kytag02: { id: 0x010b, index: '02ac', readable: 'K Twilight Tag 02', category: 'rels', },
  d_a_kytag03: { id: 0x010c, index: '02ad', readable: 'K Twilight Tag 03', category: 'rels', },
  d_a_kytag06: { id: 0x010d, index: '02b0', readable: 'K Twilight Tag 06', category: 'rels', },
  d_a_kytag07: { id: 0x010e, index: '02b1', readable: 'K Twilight Tag 07', category: 'rels', },
  d_a_kytag08: { id: 0x010f, index: '02b2', readable: 'K Twilight Tag 08', category: 'rels', },
  d_a_kytag09: { id: 0x0110, index: '02b3', readable: 'K Twilight Tag 09', category: 'rels', },
  d_a_kytag12: { id: 0x0111, index: '02b6', readable: 'K Twilight Tag 12', category: 'rels', },
  d_a_kytag13: { id: 0x0112, index: '02b7', readable: 'K Twilight Tag 13', category: 'rels', },
  d_a_kytag15: { id: 0x0113, index: '02b9', readable: 'K Twilight Tag 15', category: 'rels', },
  d_a_kytag16: { id: 0x0114, index: '02ba', readable: 'K Twilight Tag 16', category: 'rels', },
  d_a_mant: { id: 0x0115, index: '02f3', readable: 'Cape', category: 'rels', },
  d_a_mg_fshop: { id: 0x0116, index: '0137', readable: 'Minigame - Fishing Shop', category: 'rels', },
  d_a_mirror: { id: 0x0117, index: '02df', readable: 'Mirror', category: 'rels', },
  d_a_movie_player: { id: 0x0118, index: '02e0', readable: 'Movie - Player', category: 'rels', },
  d_a_myna: { id: 0x0119, index: '0232', readable: 'Myna', category: 'rels', },
  d_a_ni: { id: 0x011a, index: '0108', readable: 'Chicken', category: 'rels', },
  d_a_npc_aru: { id: 0x011b, index: '0243', readable: 'NPC - Aru', category: 'rels', notes: 'Fado', },
  d_a_npc_ash: { id: 0x011c, index: '0298', readable: 'NPC - Ash', category: 'rels', notes: 'Ashei', },
  d_a_npc_ashB: { id: 0x011d, index: '0299', readable: 'NPC - Ash B', category: 'rels', notes: 'Ashei (Yeti Garb)', },
  d_a_npc_bans: { id: 0x011e, index: '0244', readable: 'NPC - Barnes', category: 'rels', notes: 'Barnes', },
  d_a_npc_blue_ns: { id: 0x011f, index: '0240', readable: 'NPC - Blue - Night Stalker', category: 'rels', notes: 'Shadow Beast (Twili)', },
  d_a_npc_bou: { id: 0x0120, index: '0246', readable: 'NPC - Bo', category: 'rels', notes: 'Bo', },
  d_a_npc_bouS: { id: 0x0121, index: '0247', readable: 'NPC - Bo (Sumo)', category: 'rels', notes: 'Bo (Sumo)', },
  d_a_npc_cdn3: { id: 0x0122, index: '0288', readable: 'NPC - Cdn 3', category: 'rels', },
  d_a_npc_chat: { id: 0x0123, index: '028b', readable: 'NPC - Chat', category: 'rels', },
  d_a_npc_chin: { id: 0x0124, index: '02a5', readable: 'NPC - Tingle', category: 'rels', notes: 'Purlo', },
  d_a_npc_clerka: { id: 0x0125, index: '0248', readable: 'NPC - Clerk A', category: 'rels', notes: 'Chudley', },
  d_a_npc_clerkb: { id: 0x0126, index: '0249', readable: 'NPC - Clerk B', category: 'rels', notes: 'Malver', },
  d_a_npc_clerkt: { id: 0x0127, index: '024a', readable: 'NPC - Clerk (Sky Dweller)', category: 'rels', notes: 'Oocca (Shop)', },
  d_a_npc_coach: { id: 0x0128, index: '0056', readable: 'NPC - Coach', category: 'rels', },
  d_a_npc_df: { id: 0x0129, index: '0307', readable: 'NPC - Dragonfly', category: 'rels', notes: 'Dragonfly', },
  d_a_npc_doc: { id: 0x012a, index: '024e', readable: 'NPC - Doctor', category: 'rels', notes: 'Dr. Borville', },
  d_a_npc_doorboy: { id: 0x012b, index: '029f', readable: 'NPC - Door Boy', category: 'rels', },
  d_a_npc_drainSol: { id: 0x012c, index: '02a4', readable: 'NPC - Drain Soldier', category: 'rels', },
  d_a_npc_du: { id: 0x012d, index: '0138', readable: 'NPC - Duck', category: 'rels', notes: 'Duck', },
  d_a_npc_fairy: { id: 0x012e, index: '0253', readable: 'NPC - Fairy', category: 'rels', },
  d_a_npc_fguard: { id: 0x012f, index: '0294', readable: 'NPC - F Guard', category: 'rels', },
  d_a_npc_gnd: { id: 0x0130, index: '0233', readable: 'NPC - Ganondorf', category: 'rels', notes: 'Ganondorf', },
  d_a_npc_gra: { id: 0x0131, index: '0234', readable: 'NPC - Goron (Adult)', category: 'rels', notes: 'Goron (Adult)', },
  d_a_npc_grc: { id: 0x0132, index: '0235', readable: 'NPC - Goron (Child)', category: 'rels', notes: 'Goron (Child)', },
  d_a_npc_grd: { id: 0x0133, index: '0236', readable: 'NPC - Goron (Fat)', category: 'rels', },
  d_a_npc_grm: { id: 0x0134, index: '0237', readable: 'NPC - Goron Master', category: 'rels', notes: 'Goron Adult (Shop)', },
  d_a_npc_grmc: { id: 0x0135, index: '0238', readable: 'NPC - Goron Master (Child)', category: 'rels', notes: 'Goron Child (Shop)', },
  d_a_npc_gro: { id: 0x0136, index: '0239', readable: 'NPC - Goron (Old)', category: 'rels', notes: 'Gor Ebizo', },
  d_a_npc_grr: { id: 0x0137, index: '023a', readable: 'NPC - Goron (Rasta)', category: 'rels', notes: 'Gor Liggs', },
  d_a_npc_grs: { id: 0x0138, index: '023b', readable: 'NPC - Goron (Shigeru)', category: 'rels', notes: 'Gor Amoto', },
  d_a_npc_grz: { id: 0x0139, index: '023c', readable: 'NPC - Goron (Leader)', category: 'rels', notes: 'Darbus', },
  d_a_npc_guard: { id: 0x013a, index: '0297', readable: 'NPC - Guard', category: 'rels', },
  d_a_npc_gwolf: { id: 0x013b, index: '024f', readable: 'NPC - Golden Wolf', category: 'rels', notes: 'Golden Wolf', },
  d_a_npc_hanjo: { id: 0x013c, index: '0254', readable: 'NPC - Hanch', category: 'rels', notes: 'Hanch', },
  d_a_npc_henna0: { id: 0x013d, index: '0256', readable: 'NPC - Hena 0', category: 'rels', notes: 'Hena (Unused)', },
  d_a_npc_hoz: { id: 0x013e, index: '0257', readable: 'NPC - Hoz', category: 'rels', notes: 'Iza', },
  d_a_npc_impal: { id: 0x013f, index: '029d', readable: 'NPC - Impaz', category: 'rels', notes: 'Impaz', },
  d_a_npc_inko: { id: 0x0140, index: '02ff', readable: 'NPC - Parrot', category: 'rels', notes: 'Parrot', },
  d_a_npc_ins: { id: 0x0141, index: '02a6', readable: 'NPC - Insect', category: 'rels', notes: 'Agitha', },
  d_a_npc_jagar: { id: 0x0142, index: '0258', readable: 'NPC - Jagar', category: 'rels', notes: 'Jaggle', },
  d_a_npc_kasi_hana: { id: 0x0143, index: '02a1', readable: 'NPC - Boisterous - Hana', category: 'rels', notes: 'Hannah', },
  d_a_npc_kasi_kyu: { id: 0x0144, index: '02a2', readable: 'NPC - Boisterous - Kyu', category: 'rels', notes: 'Kili', },
  d_a_npc_kasi_mich: { id: 0x0145, index: '02a3', readable: 'NPC - Boisterous - Mich', category: 'rels', notes: 'Misha', },
  d_a_npc_kdk: { id: 0x0146, index: '0242', readable: 'NPC - Temporary Cutscene Guy', category: 'rels', },
  d_a_npc_kn: { id: 0x0147, index: '025a', readable: 'NPC - Knight', category: 'rels', notes: "Hero's Shade", },
  d_a_npc_knj: { id: 0x0148, index: '025c', readable: 'NPC - Sage', category: 'rels', notes: 'Sage', },
  d_a_npc_kolinb: { id: 0x0149, index: '025e', readable: 'NPC - Colin (Bed)', category: 'rels', notes: 'Colin (Bedridden)', },
  d_a_npc_ks: { id: 0x014a, index: '0060', readable: 'NPC - Kid Monkey', category: 'rels', },
  d_a_npc_kyury: { id: 0x014b, index: '025f', readable: 'NPC - Pergie', category: 'rels', notes: 'Pergie', },
  d_a_npc_len: { id: 0x014c, index: '0250', readable: 'NPC - Renado', category: 'rels', notes: 'Renado', },
  d_a_npc_lf: { id: 0x014d, index: '010f', readable: 'NPC - Lake Fish', category: 'rels', },
  d_a_npc_lud: { id: 0x014e, index: '0251', readable: 'NPC - Luda', category: 'rels', notes: 'Luda', },
  d_a_npc_midp: { id: 0x014f, index: '0261', readable: 'NPC - Midna (Princess)', category: 'rels', notes: 'Midna (Princess)', },
  d_a_npc_mk: { id: 0x0150, index: '02a8', readable: 'NPC - Monkey', category: 'rels', },
  d_a_npc_moi: { id: 0x0151, index: '0262', readable: 'NPC - Rusl', category: 'rels', notes: 'Rusl', },
  d_a_npc_moir: { id: 0x0152, index: '029c', readable: 'NPC - Rusl (Resistance)', category: 'rels', notes: 'Rusl (Resistance)', },
  d_a_npc_myna2: { id: 0x0153, index: '0286', readable: 'NPC - Myna 2', category: 'rels', },
  d_a_npc_ne: { id: 0x0154, index: '010d', readable: 'NPC - Cat', category: 'rels', notes: 'Cat', },
  d_a_npc_p2: { id: 0x0155, index: '02a9', readable: 'NPC - P2', category: 'rels', },
  d_a_npc_pachi_besu: { id: 0x0156, index: '026f', readable: 'NPC - Slingshot - Beth', category: 'rels', notes: 'Beth (Slingshot Tutorial)', },
  d_a_npc_pachi_maro: { id: 0x0157, index: '0271', readable: 'NPC - Slingshot - Malo', category: 'rels', notes: 'Malo (Slingshot Tutorial)', },
  d_a_npc_pachi_taro: { id: 0x0158, index: '0270', readable: 'NPC - Slingshot - Talo', category: 'rels', notes: 'Talo (Slingshot Tutorial)', },
  d_a_npc_passer: { id: 0x0159, index: '028f', readable: 'NPC - Passerby', category: 'rels', },
  d_a_npc_passer2: { id: 0x015a, index: '0290', readable: 'NPC - Passerby 2', category: 'rels', },
  d_a_npc_post: { id: 0x015b, index: '0291', readable: 'NPC - Postman', category: 'rels', notes: 'Postman', },
  d_a_npc_pouya: { id: 0x015c, index: '0292', readable: 'NPC - Poe Merchant', category: 'rels', notes: 'Jovani', },
  d_a_npc_prayer: { id: 0x015d, index: '02a0', readable: 'NPC - Prayer', category: 'rels', notes: 'Charlo', },
  d_a_npc_raca: { id: 0x015e, index: '0263', readable: 'NPC - Falbi', category: 'rels', notes: 'Falbi', },
  d_a_npc_rafrel: { id: 0x015f, index: '029b', readable: 'NPC - Auru', category: 'rels', notes: 'Auru', },
  d_a_npc_saru: { id: 0x0160, index: '0264', readable: 'NPC - Monkey', category: 'rels', },
  d_a_npc_seib: { id: 0x0161, index: '0265', readable: 'NPC - Spirit B', category: 'rels', },
  d_a_npc_seic: { id: 0x0162, index: '0266', readable: 'NPC - Spirit C', category: 'rels', notes: 'Eldin', },
  d_a_npc_seid: { id: 0x0163, index: '0267', readable: 'NPC - Spirit D', category: 'rels', },
  d_a_npc_seira: { id: 0x0164, index: '0268', readable: 'NPC - Sera', category: 'rels', notes: 'Sera', },
  d_a_npc_seira2: { id: 0x0165, index: '0269', readable: 'NPC - Sera 2', category: 'rels', notes: 'Sera (Shop)', },
  d_a_npc_seirei: { id: 0x0166, index: '026a', readable: 'NPC - Spirit', category: 'rels', },
  d_a_npc_shad: { id: 0x0167, index: '029a', readable: 'NPC - Shad', category: 'rels', notes: 'Shad', },
  d_a_npc_shaman: { id: 0x0168, index: '026b', readable: 'NPC - Shaman', category: 'rels', notes: 'Fanadi', },
  d_a_npc_shoe: { id: 0x0169, index: '029e', readable: 'NPC - Shoe', category: 'rels', notes: 'Soal', },
  d_a_npc_shop0: { id: 0x016a, index: '02a7', readable: 'NPC - Shop 0', category: 'rels', },
  d_a_npc_shop_maro: { id: 0x016b, index: '026c', readable: 'NPC - Shop - Malo', category: 'rels', },
  d_a_npc_sola: { id: 0x016c, index: '026d', readable: 'NPC - Soldier A', category: 'rels', },
  d_a_npc_soldierA: { id: 0x016d, index: '028c', readable: 'NPC - Soldier A', category: 'rels', },
  d_a_npc_soldierB: { id: 0x016e, index: '028d', readable: 'NPC - Soldier B', category: 'rels', },
  d_a_npc_sq: { id: 0x016f, index: '010b', readable: 'NPC - Squirrel', category: 'rels', notes: 'Squirrel', },
  d_a_npc_the: { id: 0x0170, index: '0273', readable: 'NPC - Telma', category: 'rels', notes: 'Telma', },
  d_a_npc_theB: { id: 0x0171, index: '0057', readable: 'NPC - Telma B', category: 'rels', },
  d_a_npc_tk: { id: 0x0172, index: '0100', readable: 'NPC - Hawk', category: 'rels', notes: 'Hawk', },
  d_a_npc_tkc: { id: 0x0173, index: '0276', readable: 'NPC - Sky Dweller (Child)', category: 'rels', notes: 'Ooccoo Jr.', },
  d_a_npc_tkj2: { id: 0x0174, index: '0109', readable: 'NPC - Sky Dweller 2', category: 'rels', },
  d_a_npc_tks: { id: 0x0175, index: '0275', readable: 'NPC - Sky Dweller (Small)', category: 'rels', },
  d_a_npc_toby: { id: 0x0176, index: '0278', readable: 'NPC - Fyer', category: 'rels', notes: 'Fyer', },
  d_a_npc_tr: { id: 0x0177, index: '010e', readable: 'NPC - Trout', category: 'rels', },
  d_a_npc_uri: { id: 0x0178, index: '0279', readable: 'NPC - Uli', category: 'rels', notes: 'Uli', },
  d_a_npc_worm: { id: 0x0179, index: '0101', readable: 'NPC - Worm', category: 'rels', notes: 'Worm', },
  d_a_npc_wrestler: { id: 0x017a, index: '024b', readable: 'NPC - Wrestler', category: 'rels', },
  d_a_npc_yamid: { id: 0x017b, index: '023d', readable: 'NPC - Twili (Fat)', category: 'rels', notes: 'Twili (Fat)', },
  d_a_npc_yamis: { id: 0x017c, index: '023f', readable: 'NPC - Twili (Short)', category: 'rels', notes: 'Twili (Short)', },
  d_a_npc_yamit: { id: 0x017d, index: '023e', readable: 'NPC - Twili (Tall)', category: 'rels', notes: 'Twili (Tall)', },
  d_a_npc_yelia: { id: 0x017e, index: '027a', readable: 'NPC - Ilia', category: 'rels', notes: 'Ilia', },
  d_a_npc_ykm: { id: 0x017f, index: '027b', readable: 'NPC - Snow Man', category: 'rels', notes: 'Yeto', },
  d_a_npc_ykw: { id: 0x0180, index: '027c', readable: 'NPC - Snow Woman', category: 'rels', notes: 'Yeta', },
  d_a_npc_zanb: { id: 0x0181, index: '027d', readable: 'NPC - Zant B', category: 'rels', notes: 'Zant (Unused)', },
  d_a_npc_zant: { id: 0x0182, index: '027e', readable: 'NPC - Zant', category: 'rels', },
  d_a_npc_zelR: { id: 0x0183, index: '0280', readable: 'NPC - Zelda (Robe)', category: 'rels', notes: 'Zelda (Cloaked & Hooded)', },
  d_a_npc_zelRo: { id: 0x0184, index: '0281', readable: 'NPC - Zelda (Robe - Off)', category: 'rels', notes: 'Zelda (Cloaked)', },
  d_a_npc_zelda: { id: 0x0185, index: '027f', readable: 'NPC - Zelda', category: 'rels', notes: 'Zelda', },
  d_a_npc_zra: { id: 0x0186, index: '00e5', readable: 'NPC - Zora (Adult)', category: 'rels', },
  d_a_npc_zrc: { id: 0x0187, index: '0283', readable: 'NPC - Zora (Child)', category: 'rels', notes: 'Ralis', },
  d_a_npc_zrz: { id: 0x0188, index: '0284', readable: 'NPC - Zora (Leader)', category: 'rels', notes: 'Rutela', },
  d_a_obj_Lv5Key: { id: 0x0189, index: '0115', readable: 'Object - Level 5 Key', category: 'rels', },
  d_a_obj_Turara: { id: 0x018a, index: '0050', readable: 'Object - Icicle', category: 'rels', },
  d_a_obj_TvCdlst: { id: 0x018b, index: '003b', readable: 'Object - Toaru Village Torch Stand', category: 'rels', },
  d_a_obj_Y_taihou: { id: 0x018c, index: '0091', readable: 'Object - Snow - Cannon', category: 'rels', },
  d_a_obj_amiShutter: { id: 0x018d, index: '0047', readable: 'Object - Mesh Shutter', category: 'rels', },
  d_a_obj_ari: { id: 0x018e, index: '0147', readable: 'Object - Ant', category: 'rels', notes: 'Ant', },
  d_a_obj_automata: { id: 0x018f, index: '02f9', readable: 'Object - Automata', category: 'rels', notes: "Falbi's Music Box", },
  d_a_obj_avalanche: { id: 0x0190, index: '00ad', readable: 'Object - Avalanche', category: 'rels', },
  d_a_obj_balloon: { id: 0x0191, index: '011c', readable: 'Object - Balloon', category: 'rels', },
  d_a_obj_barDesk: { id: 0x0192, index: '008f', readable: 'Object - Bar Desk', category: 'rels', },
  d_a_obj_batta: { id: 0x0193, index: '0149', readable: 'Object - Grasshopper', category: 'rels', notes: 'Grasshopper', },
  d_a_obj_bbox: { id: 0x0194, index: '007a', readable: 'Object - B Box', category: 'rels', },
  d_a_obj_bed: { id: 0x0195, index: '012c', readable: 'Object - Bed', category: 'rels', },
  d_a_obj_bemos: { id: 0x0196, index: '0084', readable: 'Object - Beamos', category: 'rels', },
  d_a_obj_bhbridge: { id: 0x0197, index: '0069', readable: 'Object - Bh Bridge', category: 'rels', },
  d_a_obj_bk_leaf: { id: 0x0198, index: '02c0', readable: 'Object - Baba Stem - Leaf', category: 'rels', },
  d_a_obj_bky_rock: { id: 0x0199, index: '0103', readable: 'Object - Bomb Shack - Rock', category: 'rels', },
  d_a_obj_bmWindow: { id: 0x019a, index: '0042', readable: 'Object - Bm Window', category: 'rels', },
  d_a_obj_bmshutter: { id: 0x019b, index: '005f', readable: 'Object - Bm Shutter', category: 'rels', },
  d_a_obj_bombf: { id: 0x019c, index: '02bf', readable: 'Object - Bomb Flower', category: 'rels', notes: 'Bomb Flower', },
  d_a_obj_boumato: { id: 0x019d, index: '012d', readable: 'Object - Stick Target', category: 'rels', },
  d_a_obj_brg: { id: 0x019e, index: '002c', readable: 'Object - Bridge', category: 'rels', },
  d_a_obj_bsGate: { id: 0x019f, index: '0046', readable: 'Object - Boss Gate', category: 'rels', },
  d_a_obj_bubblePilar: { id: 0x01a0, index: '0192', readable: 'Object - Bubble Pillar', category: 'rels', },
  d_a_obj_catdoor: { id: 0x01a1, index: '00b9', readable: 'Object - Cat Door', category: 'rels', notes: 'Cat Door', },
  d_a_obj_cb: { id: 0x01a2, index: '002a', readable: 'Object - Castle Block', category: 'rels', },
  d_a_obj_cblock: { id: 0x01a3, index: '007e', readable: 'Object - Chain Block', category: 'rels', },
  d_a_obj_cdoor: { id: 0x01a4, index: '0034', readable: 'Object - Chain Door', category: 'rels', },
  d_a_obj_chandelier: { id: 0x01a5, index: '00e6', readable: 'Object - Chandelier', category: 'rels', },
  d_a_obj_chest: { id: 0x01a6, index: '0083', readable: 'Object - Chest', category: 'rels', },
  d_a_obj_cho: { id: 0x01a7, index: '0141', readable: 'Object - Butterfly', category: 'rels', },
  d_a_obj_cowdoor: { id: 0x01a8, index: '005d', readable: 'Object - Cow Door', category: 'rels', },
  d_a_obj_crope: { id: 0x01a9, index: '02be', readable: 'Object - C Rope', category: 'rels', notes: 'Wolf Tightrope', },
  d_a_obj_crvfence: { id: 0x01aa, index: '0070', readable: 'Object - Caravan Fence', category: 'rels', },
  d_a_obj_crvgate: { id: 0x01ab, index: '006f', readable: 'Object - Caravan Gate', category: 'rels', },
  d_a_obj_crvhahen: { id: 0x01ac, index: '0071', readable: 'Object - Caravan Fragment', category: 'rels', },
  d_a_obj_crvlh_down: { id: 0x01ad, index: '0074', readable: 'Object - Caravan Lookout Hut - Down', category: 'rels', },
  d_a_obj_crvlh_up: { id: 0x01ae, index: '0073', readable: 'Object - Caravan Lookout Hut - Up', category: 'rels', },
  d_a_obj_crvsteel: { id: 0x01af, index: '0072', readable: 'Object - Caravan Steel', category: 'rels', },
  d_a_obj_crystal: { id: 0x01b0, index: '01a4', readable: 'Object - Crystal', category: 'rels', },
  d_a_obj_cwall: { id: 0x01b1, index: '007f', readable: 'Object - Chain Wall', category: 'rels', },
  d_a_obj_damCps: { id: 0x01b2, index: '0175', readable: 'Object - Dam Cps', category: 'rels', },
  d_a_obj_dan: { id: 0x01b3, index: '0144', readable: 'Object - Pillbug', category: 'rels', },
  d_a_obj_digholl: { id: 0x01b4, index: '0052', readable: 'Object - Dig Hole', category: 'rels', notes: 'Dig Spot - Passage', },
  d_a_obj_digsnow: { id: 0x01b5, index: '0090', readable: 'Object - Dig Snow', category: 'rels', notes: 'Dig Spot - Snow', },
  d_a_obj_dmelevator: { id: 0x01b6, index: '0092', readable: 'Object - Death Mountain Elevator', category: 'rels', },
  d_a_obj_drop: { id: 0x01b7, index: '021f', readable: 'Object - Drop', category: 'rels', },
  d_a_obj_dust: { id: 0x01b8, index: '0076', readable: 'Object - Dust', category: 'rels', },
  d_a_obj_enemy_create: { id: 0x01b9, index: '0068', readable: 'Object - Enemy - Create', category: 'rels', },
  d_a_obj_fallobj: { id: 0x01ba, index: '00aa', readable: 'Object - Fall Object', category: 'rels', },
  d_a_obj_fan: { id: 0x01bb, index: '0186', readable: 'Object - Fan', category: 'rels', },
  d_a_obj_fchain: { id: 0x01bc, index: '0158', readable: 'Object - F Chain', category: 'rels', },
  d_a_obj_fireWood: { id: 0x01bd, index: '0169', readable: 'Object - Firewood', category: 'rels', },
  d_a_obj_fireWood2: { id: 0x01be, index: '016a', readable: 'Object - Firewood 2', category: '', },
  d_a_obj_firepillar: { id: 0x01bf, index: '015d', readable: 'Object - Fire Pillar', category: 'rels', },
  d_a_obj_firepillar2: { id: 0x01c0, index: '015e', readable: 'Object - Fire Pillar 2', category: 'rels', },
  d_a_obj_flag: { id: 0x01c1, index: '013b', readable: 'Object - Flag', category: 'rels', },
  d_a_obj_flag2: { id: 0x01c2, index: '013c', readable: 'Object - Flag 2', category: 'rels', },
  d_a_obj_flag3: { id: 0x01c3, index: '013d', readable: 'Object - Flag 3', category: 'rels', },
  d_a_obj_food: { id: 0x01c4, index: '0110', readable: 'Object - Food', category: 'rels', },
  d_a_obj_fw: { id: 0x01c5, index: '02f0', readable: 'Object - Firewood', category: 'rels', },
  d_a_obj_gadget: { id: 0x01c6, index: '02fa', readable: 'Object - Gadget', category: 'rels', },
  d_a_obj_ganonwall: { id: 0x01c7, index: '0196', readable: 'Object - Ganon Wall', category: 'rels', },
  d_a_obj_ganonwall2: { id: 0x01c8, index: '00c0', readable: 'Object - Ganon Wall 2', category: 'rels', },
  d_a_obj_gb: { id: 0x01c9, index: '002d', readable: 'Object - Ganondorf Barrier', category: 'rels', },
  d_a_obj_geyser: { id: 0x01ca, index: '0167', readable: 'Object - Geyser', category: 'rels', },
  d_a_obj_glowSphere: { id: 0x01cb, index: '017b', readable: 'Object - Glow Sphere', category: 'rels', },
  d_a_obj_gm: { id: 0x01cc, index: '002e', readable: 'Object - Gohma', category: 'rels', notes: 'Gohma Egg Container', },
  d_a_obj_goGate: { id: 0x01cd, index: '003e', readable: 'Object - Goron Gate', category: 'rels', },
  d_a_obj_gomikabe: { id: 0x01ce, index: '013e', readable: 'Object - Garbage Wall', category: 'rels', },
  d_a_obj_gra2: { id: 0x01cf, index: '0021', readable: 'Object - Goron (Adult) 2', category: 'rels', },
  d_a_obj_graWall: { id: 0x01d0, index: '008b', readable: 'Object - Goron (Adult) Wall', category: 'rels', },
  d_a_obj_gra_rock: { id: 0x01d1, index: '0089', readable: 'Object - Goron (Adult) - Rock', category: 'rels', },
  d_a_obj_grave_stone: { id: 0x01d2, index: '0087', readable: 'Object - Grave - Stone', category: 'rels', },
  d_a_obj_groundwater: { id: 0x01d3, index: '0035', readable: 'Object - Groundwater', category: 'rels', },
  d_a_obj_grz_rock: { id: 0x01d4, index: '008a', readable: 'Object - Goron (Leader) - Rock', category: 'rels', },
  d_a_obj_h_saku: { id: 0x01d5, index: '014c', readable: 'Object - H - Fence', category: 'rels', },
  d_a_obj_hakai_brl: { id: 0x01d6, index: '01a3', readable: 'Object - Destructable - Barrel', category: 'rels', },
  d_a_obj_hakai_ftr: { id: 0x01d7, index: '01a2', readable: 'Object - Destructable - Furniture', category: 'rels', },
  d_a_obj_hasu2: { id: 0x01d8, index: '00cb', readable: 'Object - Lilypad 2', category: 'rels', },
  d_a_obj_hata: { id: 0x01d9, index: '01a8', readable: 'Object - Flag', category: 'rels', },
  d_a_obj_hb: { id: 0x01da, index: '02fe', readable: 'Object - Serpent Baba', category: 'rels', },
  d_a_obj_hbombkoya: { id: 0x01db, index: '00d8', readable: 'Object - Destructable Bomb Shack', category: 'rels', },
  d_a_obj_heavySw: { id: 0x01dc, index: '003d', readable: 'Object - Heavy Switch', category: 'rels', },
  d_a_obj_hfuta: { id: 0x01dd, index: '0061', readable: 'Object - Crawling Cover', category: 'rels', },
  d_a_obj_hsTarget: { id: 0x01de, index: '003c', readable: 'Object - Hookshot Target', category: 'rels', },
  d_a_obj_ice_l: { id: 0x01df, index: '0066', readable: 'Object - Ice - Large', category: 'rels', },
  d_a_obj_ice_s: { id: 0x01e0, index: '0067', readable: 'Object - Ice - Small', category: 'rels', },
  d_a_obj_iceblock: { id: 0x01e1, index: '00df', readable: 'Object - Ice Block', category: 'rels', },
  d_a_obj_iceleaf: { id: 0x01e2, index: '0187', readable: 'Object - Ice Leaf', category: 'rels', },
  d_a_obj_ihasi: { id: 0x01e3, index: '00de', readable: 'Object - I Bridge', category: 'rels', },
  d_a_obj_ikada: { id: 0x01e4, index: '0065', readable: 'Object - Raft', category: 'rels', },
  d_a_obj_inobone: { id: 0x01e5, index: '015f', readable: 'Object - Boar Bone', category: 'rels', },
  d_a_obj_ita: { id: 0x01e6, index: '0077', readable: 'Object - Plank', category: 'rels', },
  d_a_obj_itamato: { id: 0x01e7, index: '012e', readable: 'Object - Plank Target', category: 'rels', },
  d_a_obj_kabuto: { id: 0x01e8, index: '0140', readable: 'Object - Beetle', category: 'rels', notes: 'Beetle', },
  d_a_obj_kag: { id: 0x01e9, index: '0148', readable: 'Object - Dayfly', category: 'rels', notes: 'Dayfly', },
  d_a_obj_kage: { id: 0x01ea, index: '011a', readable: 'Object - Cage', category: 'rels', },
  d_a_obj_kago: { id: 0x01eb, index: '02fb', readable: 'Object - Basket', category: 'rels', },
  d_a_obj_kaisou: { id: 0x01ec, index: '006a', readable: 'Object - Seaweed', category: 'rels', },
  d_a_obj_kamakiri: { id: 0x01ed, index: '0145', readable: 'Object - Mantis', category: 'rels', notes: 'Mantis', },
  d_a_obj_kantera: { id: 0x01ee, index: '021a', readable: 'Object - Lantern', category: 'rels', },
  d_a_obj_katatsumuri: { id: 0x01ef, index: '014b', readable: 'Object - Snail', category: 'rels', notes: 'Snail', },
  d_a_obj_kazeneko: { id: 0x01f0, index: '014e', readable: 'Object - Wind Cat', category: 'rels', },
  d_a_obj_kbox: { id: 0x01f1, index: '02ef', readable: 'Object - Crate', category: 'rels', },
  d_a_obj_key: { id: 0x01f2, index: '0113', readable: 'Object - Key', category: 'rels', },
  d_a_obj_keyhole: { id: 0x01f3, index: '0114', readable: 'Object - Key Hole', category: 'rels', },
  d_a_obj_ki: { id: 0x01f4, index: '0111', readable: 'Object - Tree', category: 'rels', },
  d_a_obj_kiPot: { id: 0x01f5, index: '016d', readable: 'Object - Coro Pot', category: 'rels', },
  d_a_obj_kita: { id: 0x01f6, index: '0112', readable: 'Object - Wind Plank', category: 'rels', },
  d_a_obj_kjgjs: { id: 0x01f7, index: '00dd', readable: 'Object - Kjgjs', category: 'rels', },
  d_a_obj_kkanban: { id: 0x01f8, index: '00e3', readable: 'Object - Kakariko Sign', category: 'rels', },
  d_a_obj_knBullet: { id: 0x01f9, index: '025b', readable: 'Object - Knight Bullet', category: 'rels', },
  d_a_obj_kshutter: { id: 0x01fa, index: '0055', readable: 'Object - Key Shutter', category: 'rels', },
  d_a_obj_kuwagata: { id: 0x01fb, index: '0142', readable: 'Object - Stag Beetle', category: 'rels', },
  d_a_obj_kwheel00: { id: 0x01fc, index: '00c7', readable: 'Object - K Wheel 00', category: 'rels', },
  d_a_obj_kwheel01: { id: 0x01fd, index: '00c8', readable: 'Object - K Wheel 01', category: 'rels', },
  d_a_obj_kznkarm: { id: 0x01fe, index: '014f', readable: 'Object - Weather Vane Arm', category: 'rels', },
  d_a_obj_laundry: { id: 0x01ff, index: '0155', readable: 'Object - Laundry', category: 'rels', },
  d_a_obj_laundry_rope: { id: 0x0200, index: '0152', readable: 'Object - Laundry - Rope', category: 'rels', },
  d_a_obj_lbox: { id: 0x0201, index: '0027', readable: 'Object - L Box', category: 'rels', },
  d_a_obj_lp: { id: 0x0202, index: '0116', readable: 'Object - Lilypad', category: 'rels', },
  d_a_obj_lv1Candle00: { id: 0x0203, index: '0039', readable: 'Object - Level 1 Candle 00', category: 'rels', },
  d_a_obj_lv1Candle01: { id: 0x0204, index: '003a', readable: 'Object - Level 1 Candle 01', category: 'rels', },
  d_a_obj_lv3Candle: { id: 0x0205, index: '0172', readable: 'Object - Level 3 Candle', category: 'rels', },
  d_a_obj_lv3Water: { id: 0x0206, index: '00d5', readable: 'Object - Level 3 Water', category: 'rels', },
  d_a_obj_lv3Water2: { id: 0x0207, index: '00d6', readable: 'Object - Level 3 Water 2', category: 'rels', },
  d_a_obj_lv3WaterB: { id: 0x0208, index: '00d7', readable: 'Object - Level 3 Water (Boss)', category: 'rels', },
  d_a_obj_lv3saka00: { id: 0x0209, index: '00d4', readable: 'Object - Level 3 Slope 00', category: 'rels', },
  d_a_obj_lv3waterEff: { id: 0x020a, index: '017f', readable: 'Object - Level 3 Water Effect', category: 'rels', },
  d_a_obj_lv4CandleDemoTag: { id: 0x020b, index: '0174', readable: 'Object - Level 4 Candle Cutscene Tag', category: 'rels', },
  d_a_obj_lv4CandleTag: { id: 0x020c, index: '0173', readable: 'Object - Level 4 Candle Tag', category: 'rels', },
  d_a_obj_lv4EdShutter: { id: 0x020d, index: '009b', readable: 'Object - Level 4 Ed Shutter', category: 'rels', },
  d_a_obj_lv4Gate: { id: 0x020e, index: '009c', readable: 'Object - Level 4 Gate', category: 'rels', },
  d_a_obj_lv4HsTarget: { id: 0x020f, index: '009f', readable: 'Object - Level 4 Hookshot Target', category: 'rels', },
  d_a_obj_lv4PoGate: { id: 0x0210, index: '009d', readable: 'Object - Level 4 Poe Gate', category: 'rels', },
  d_a_obj_lv4RailWall: { id: 0x0211, index: '00bc', readable: 'Object - Level 4 Rail Wall', category: 'rels', },
  d_a_obj_lv4SlideWall: { id: 0x0212, index: '009e', readable: 'Object - Level 4 Slide Wall', category: 'rels', },
  d_a_obj_lv4bridge: { id: 0x0213, index: '00c1', readable: 'Object - Level 4 Bridge', category: 'rels', },
  d_a_obj_lv4chandelier: { id: 0x0214, index: '00d3', readable: 'Object - Level 4 Chandelier', category: 'rels', },
  d_a_obj_lv4digsand: { id: 0x0215, index: '00a9', readable: 'Object - Level 4 Dig Sand', category: 'rels', },
  d_a_obj_lv4floor: { id: 0x0216, index: '00c2', readable: 'Object - Level 4 Floor', category: 'rels', },
  d_a_obj_lv4gear: { id: 0x0217, index: '0183', readable: 'Object - Level 4 Gear', category: 'rels', },
  d_a_obj_lv4prelvtr: { id: 0x0218, index: '00ca', readable: 'Object - Level 4 Pr Elevator', category: 'rels', },
  d_a_obj_lv4prwall: { id: 0x0219, index: '00d0', readable: 'Object - Level 4 Pr Wall', category: 'rels', },
  d_a_obj_lv4sand: { id: 0x021a, index: '00bd', readable: 'Object - Level 4 Sand', category: 'rels', },
  d_a_obj_lv5FloorBoard: { id: 0x021b, index: '004f', readable: 'Object - Level 5 Floorboard', category: 'rels', },
  d_a_obj_lv5IceWall: { id: 0x021c, index: '004d', readable: 'Object - Level 5 Ice Wall', category: 'rels', },
  d_a_obj_lv5SwIce: { id: 0x021d, index: '004e', readable: 'Object - Level 5 Switch Ice', category: 'rels', },
  d_a_obj_lv5ychndlr: { id: 0x021e, index: '00c9', readable: 'Object - Level 5 Snow Chandalier', category: 'rels', },
  d_a_obj_lv5yiblltray: { id: 0x021f, index: '00cc', readable: 'Object - Level 5 Snow Iron Ball Tray', category: 'rels', },
  d_a_obj_lv6ChangeGate: { id: 0x0220, index: '0098', readable: 'Object - Level 6 Change Gate', category: 'rels', },
  d_a_obj_lv6FurikoTrap: { id: 0x0221, index: '0099', readable: 'Object - Level 6 Pendulum Trap', category: 'rels', },
  d_a_obj_lv6Lblock: { id: 0x0222, index: '0097', readable: 'Object - Level 6 L Block', category: 'rels', },
  d_a_obj_lv6SwGate: { id: 0x0223, index: '0096', readable: 'Object - Level 6 Switch Gate', category: 'rels', },
  d_a_obj_lv6SzGate: { id: 0x0224, index: '009a', readable: 'Object - Level 6 Stone Statue Gate', category: 'rels', },
  d_a_obj_lv6Tenbin: { id: 0x0225, index: '0095', readable: 'Object - Level 6 Scale', category: 'rels', },
  d_a_obj_lv6TogeRoll: { id: 0x0226, index: '0093', readable: 'Object - Level 6 Spike Roll', category: 'rels', },
  d_a_obj_lv6TogeTrap: { id: 0x0227, index: '0094', readable: 'Object - Level 6 Spike Trap', category: 'rels', },
  d_a_obj_lv6bemos: { id: 0x0228, index: '008d', readable: 'Object - Level 6 Beamos', category: 'rels', },
  d_a_obj_lv6bemos2: { id: 0x0229, index: '008e', readable: 'Object - Level 6 Beamos 2', category: 'rels', },
  d_a_obj_lv6egate: { id: 0x022a, index: '00cd', readable: 'Object - Level 6 Elevator Gate', category: 'rels', },
  d_a_obj_lv6elevta: { id: 0x022b, index: '001b', readable: 'Object - Level 6 Elevator', category: 'rels', },
  d_a_obj_lv6swturn: { id: 0x022c, index: '001f', readable: 'Object - Level 6 Switch Turn', category: 'rels', },
  d_a_obj_lv7BsGate: { id: 0x022d, index: '00a1', readable: 'Object - Level 7 Boss Gate', category: 'rels', },
  d_a_obj_lv7PropellerY: { id: 0x022e, index: '00a0', readable: 'Object - Level 7 Propeller Y', category: 'rels', },
  d_a_obj_lv7bridge: { id: 0x022f, index: '00b5', readable: 'Object - Level 7 Bridge', category: 'rels', },
  d_a_obj_lv8KekkaiTrap: { id: 0x0230, index: '00a3', readable: 'Object - Level 8 Barrier Trap', category: 'rels', },
  d_a_obj_lv8Lift: { id: 0x0231, index: '00a4', readable: 'Object - Level 8 Lift', category: 'rels', },
  d_a_obj_lv8OptiLift: { id: 0x0232, index: '00a2', readable: 'Object - Level 8 Opti Lift', category: 'rels', },
  d_a_obj_lv8UdFloor: { id: 0x0233, index: '00a5', readable: 'Object - Level 8 Ud Floor', category: 'rels', },
  d_a_obj_lv9SwShutter: { id: 0x0234, index: '00a6', readable: 'Object - Level 9 Switch Shutter', category: 'rels', },
  d_a_obj_magLift: { id: 0x0235, index: '0037', readable: 'Object - Magnet Lift', category: 'rels', },
  d_a_obj_magLiftRot: { id: 0x0236, index: '0038', readable: 'Object - Magnet Lift (Rotating)', category: 'rels', },
  d_a_obj_maki: { id: 0x0237, index: '002b', readable: 'Object - Bundle', category: 'rels', },
  d_a_obj_master_sword: { id: 0x0238, index: '0184', readable: 'Object - Master - Sword', category: 'rels', },
  d_a_obj_mato: { id: 0x0239, index: '013a', readable: 'Object - Target', category: 'rels', },
  d_a_obj_mhole: { id: 0x023a, index: '0161', readable: 'Object - Magnet Hole', category: 'rels', },
  d_a_obj_mie: { id: 0x023b, index: '0131', readable: 'Object - Mie', category: 'rels', notes: 'Gengle', },
  d_a_obj_mirror_6pole: { id: 0x023c, index: '00b2', readable: 'Object - Mirror - 6 Pole', category: 'rels', },
  d_a_obj_mirror_chain: { id: 0x023d, index: '00b1', readable: 'Object - Mirror - Chain', category: 'rels', },
  d_a_obj_mirror_sand: { id: 0x023e, index: '00af', readable: 'Object - Mirror - Sand', category: 'rels', },
  d_a_obj_mirror_screw: { id: 0x023f, index: '00ae', readable: 'Object - Mirror - Screw', category: 'rels', },
  d_a_obj_mirror_table: { id: 0x0240, index: '00b0', readable: 'Object - Mirror - Table', category: 'rels', },
  d_a_obj_msima: { id: 0x0241, index: '007b', readable: 'Object - Magnet Island', category: 'rels', },
  d_a_obj_mvstair: { id: 0x0242, index: '005c', readable: 'Object - Moving Stairs', category: 'rels', },
  d_a_obj_myogan: { id: 0x0243, index: '007c', readable: 'Object - M Lava', category: 'rels', },
  d_a_obj_nagaisu: { id: 0x0244, index: '019c', readable: 'Object - Couch', category: 'rels', },
  d_a_obj_nan: { id: 0x0245, index: '0143', readable: 'Object - Phasmid', category: 'rels', },
  d_a_obj_ndoor: { id: 0x0246, index: '0128', readable: 'Object - Cat Door', category: 'rels', },
  d_a_obj_nougu: { id: 0x0247, index: '012f', readable: 'Object - Farm Implement', category: 'rels', },
  d_a_obj_octhashi: { id: 0x0248, index: '006d', readable: 'Object - Octaeel Pillar', category: 'rels', },
  d_a_obj_oiltubo: { id: 0x0249, index: '011e', readable: 'Object - Oil Jar', category: 'rels', },
  d_a_obj_onsen: { id: 0x024a, index: '0082', readable: 'Object - Hotspring', category: 'rels', },
  d_a_obj_onsenFire: { id: 0x024b, index: '008c', readable: 'Object - Hotspring Fire', category: 'rels', },
  d_a_obj_onsenTaru: { id: 0x024c, index: '016c', readable: 'Object - Hotspring Barrel', category: 'rels', },
  d_a_obj_pdoor: { id: 0x024d, index: '00be', readable: 'Object - Push Door', category: 'rels', },
  d_a_obj_pdtile: { id: 0x024e, index: '00ce', readable: 'Object - P Drop Tile', category: 'rels', },
  d_a_obj_pdwall: { id: 0x024f, index: '00cf', readable: 'Object - Pd Wall', category: 'rels', },
  d_a_obj_picture: { id: 0x0250, index: '019e', readable: 'Object - Picture', category: 'rels', },
  d_a_obj_pillar: { id: 0x0251, index: '0033', readable: 'Object - Pillar', category: 'rels', },
  d_a_obj_pleaf: { id: 0x0252, index: '02f5', readable: 'Object - Pumpkin Leaf', category: 'rels', },
  d_a_obj_poCandle: { id: 0x0253, index: '00a8', readable: 'Object - Poe Candle', category: 'rels', },
  d_a_obj_poFire: { id: 0x0254, index: '0179', readable: 'Object - Poe Fire', category: '', },
  d_a_obj_poTbox: { id: 0x0255, index: '0193', readable: 'Object - Poe Treasure Chest', category: 'rels', },
  d_a_obj_prop: { id: 0x0256, index: '0197', readable: 'Object - Propeller', category: 'rels', },
  d_a_obj_pumpkin: { id: 0x0257, index: '02f8', readable: 'Object - Pumpkin', category: 'rels', },
  d_a_obj_rcircle: { id: 0x0258, index: '019d', readable: 'Object - River Circle', category: 'rels', },
  d_a_obj_rfHole: { id: 0x0259, index: '0043', readable: 'Object - Roof Hole', category: 'rels', },
  d_a_obj_rgate: { id: 0x025a, index: '0081', readable: 'Object - Rider Gate', category: 'rels', },
  d_a_obj_riverrock: { id: 0x025b, index: '0075', readable: 'Object - River Rock', category: 'rels', },
  d_a_obj_rock: { id: 0x025c, index: '0118', readable: 'Object - Rock', category: 'rels', },
  d_a_obj_rotBridge: { id: 0x025d, index: '0036', readable: 'Object - Rotating Bridge', category: 'rels', },
  d_a_obj_rotTrap: { id: 0x025e, index: '004b', readable: 'Object - Rotating Trap', category: 'rels', },
  d_a_obj_roten: { id: 0x025f, index: '011f', readable: 'Object - Stall', category: 'rels', },
  d_a_obj_rstair: { id: 0x0260, index: '00c5', readable: 'Object - R Stair', category: 'rels', },
  d_a_obj_rw: { id: 0x0261, index: '0220', readable: 'Object - Roast Wild Boar', category: 'rels', },
  d_a_obj_saidan: { id: 0x0262, index: '0040', readable: 'Object - Altar', category: 'rels', },
  d_a_obj_sakuita: { id: 0x0263, index: '0154', readable: 'Object - Fence Plank', category: 'rels', },
  d_a_obj_sakuita_rope: { id: 0x0264, index: '0153', readable: 'Object - Fence Plank - Rope', category: 'rels', },
  d_a_obj_scannon: { id: 0x0265, index: '018c', readable: 'Object - Sky Cannon', category: 'rels', },
  d_a_obj_scannon_crs: { id: 0x0266, index: '018e', readable: 'Object - Sky Cannon - Crash', category: 'rels', },
  d_a_obj_scannon_ten: { id: 0x0267, index: '01a5', readable: 'Object - Sky Cannon - Sky', category: 'rels', },
  d_a_obj_sekidoor: { id: 0x0268, index: '0132', readable: 'Object - Stone Statue Door', category: 'rels', },
  d_a_obj_sekizo: { id: 0x0269, index: '0133', readable: 'Object - Stone Statue', category: 'rels', },
  d_a_obj_sekizoa: { id: 0x026a, index: '0020', readable: 'Object - Stone Statue A', category: 'rels', },
  d_a_obj_shield: { id: 0x026b, index: '021c', readable: 'Object - Shield', category: 'rels', },
  d_a_obj_sm_door: { id: 0x026c, index: '012b', readable: 'Object - Sacred Meadow - Door', category: 'rels', },
  d_a_obj_smallkey: { id: 0x026d, index: '0219', readable: 'Object - Small Key', category: 'rels', },
  d_a_obj_smgdoor: { id: 0x026e, index: '00ab', readable: 'Object - Sacred Meadow Grove Door', category: 'rels', },
  d_a_obj_smoke: { id: 0x026f, index: '0176', readable: 'Object - Smoke', category: 'rels', },
  d_a_obj_smtile: { id: 0x0270, index: '0134', readable: 'Object - Sacred Meadow Tile', category: 'rels', },
  d_a_obj_smw_stone: { id: 0x0271, index: '018d', readable: 'Object - Sacred Meadow Wind - Stone', category: 'rels', },
  d_a_obj_snowEffTag: { id: 0x0272, index: '018f', readable: 'Object - Snow Effect Tag', category: 'rels', },
  d_a_obj_snow_soup: { id: 0x0273, index: '019b', readable: 'Object - Snow - Soup', category: 'rels', },
  d_a_obj_so: { id: 0x0274, index: '001c', readable: 'Object - Monkey Cage', category: 'rels', },
  d_a_obj_spinLift: { id: 0x0275, index: '0041', readable: 'Object - Spinner Lift', category: 'rels', },
  d_a_obj_ss_drink: { id: 0x0276, index: '0120', readable: 'Object - SS - Drink', category: 'rels', },
  d_a_obj_ss_item: { id: 0x0277, index: '0121', readable: 'Object - SS - Item', category: 'rels', },
  d_a_obj_stairBlock: { id: 0x0278, index: '0166', readable: 'Object - Stair Block', category: 'rels', },
  d_a_obj_stone: { id: 0x0279, index: '02fd', readable: 'Object - Stone', category: 'rels', },
  d_a_obj_stopper: { id: 0x027a, index: '0160', readable: 'Object - Stopper', category: 'rels', },
  d_a_obj_stopper2: { id: 0x027b, index: '00e7', readable: 'Object - Stopper 2', category: 'rels', },
  d_a_obj_suisya: { id: 0x027c, index: '011d', readable: 'Object - Water Wheel', category: 'rels', },
  d_a_obj_sw: { id: 0x027d, index: '00f1', readable: 'Object - Switch', category: 'rels', },
  d_a_obj_swBallA: { id: 0x027e, index: '0199', readable: 'Object - Switch Ball A', category: 'rels', },
  d_a_obj_swBallB: { id: 0x027f, index: '019a', readable: 'Object - Switch Ball B', category: 'rels', },
  d_a_obj_swBallC: { id: 0x0280, index: '01a6', readable: 'Object - Switch Ball C', category: 'rels', },
  d_a_obj_swLight: { id: 0x0281, index: '00ac', readable: 'Object - Switch Light', category: 'rels', },
  d_a_obj_swchain: { id: 0x0282, index: '016f', readable: 'Object - Switch Chain', category: 'rels', },
  d_a_obj_swhang: { id: 0x0283, index: '00c4', readable: 'Object - Switch Hang', category: 'rels', },
  d_a_obj_sword: { id: 0x0284, index: '01ac', readable: 'Object - Sword', category: 'rels', },
  d_a_obj_swpush2: { id: 0x0285, index: '0017', readable: 'Object - Switch Push 2', category: 'rels', },
  d_a_obj_swspinner: { id: 0x0286, index: '00b3', readable: 'Object - Switch (Spinner)', category: 'rels', },
  d_a_obj_swturn: { id: 0x0287, index: '001e', readable: 'Object - Switch Turn', category: 'rels', },
  d_a_obj_syRock: { id: 0x0288, index: '0045', readable: 'Object - Stalactite Rock', category: 'rels', },
  d_a_obj_szbridge: { id: 0x0289, index: '00d9', readable: 'Object - Stone Statue Bridge', category: 'rels', },
  d_a_obj_taFence: { id: 0x028a, index: '003f', readable: 'Object - Ta Fence', category: 'rels', },
  d_a_obj_table: { id: 0x028b, index: '00b8', readable: 'Object - Table', category: 'rels', },
  d_a_obj_takaraDai: { id: 0x028c, index: '00b7', readable: 'Object - Treasure Platform', category: 'rels', },
  d_a_obj_tatigi: { id: 0x028d, index: '0117', readable: 'Object - Standing Wood', category: 'rels', },
  d_a_obj_ten: { id: 0x028e, index: '0146', readable: 'Object - Sky', category: 'rels', },
  d_a_obj_testcube: { id: 0x028f, index: '0054', readable: 'Object - Test Cube', category: 'rels', },
  d_a_obj_tgake: { id: 0x0290, index: '00ba', readable: 'Object - Howling Cliff', category: 'rels', },
  d_a_obj_thashi: { id: 0x0291, index: '006e', readable: 'Object - T Pillar', category: 'rels', },
  d_a_obj_thdoor: { id: 0x0292, index: '00b4', readable: 'Object - Thelma Door', category: 'rels', },
  d_a_obj_timeFire: { id: 0x0293, index: '0194', readable: 'Object - Time Fire', category: 'rels', },
  d_a_obj_tks: { id: 0x0294, index: '0277', readable: 'Object - Sky Dweller (Small)', category: 'rels', },
  d_a_obj_tmoon: { id: 0x0295, index: '0195', readable: 'Object - Howling Moon', category: 'rels', },
  d_a_obj_toaru_maki: { id: 0x0296, index: '01a9', readable: 'Object - Toaru - Bundle', category: 'rels', },
  d_a_obj_toby: { id: 0x0297, index: '002f', readable: 'Object - Flying Floor', category: 'rels', },
  d_a_obj_tobyhouse: { id: 0x0298, index: '00a7', readable: 'Object - Fyer House', category: 'rels', },
  d_a_obj_togeTrap: { id: 0x0299, index: '004a', readable: 'Object - Spike Trap', category: 'rels', },
  d_a_obj_tombo: { id: 0x029a, index: '014a', readable: 'Object - Dragonfly', category: 'rels', notes: 'Dragonfly', },
  d_a_obj_tornado: { id: 0x029b, index: '015b', readable: 'Object - Tornado', category: 'rels', },
  d_a_obj_tornado2: { id: 0x029c, index: '015c', readable: 'Object - Tornado 2', category: 'rels', },
  d_a_obj_tp: { id: 0x029d, index: '0030', readable: 'Object - Twilight Pole', category: 'rels', },
  d_a_obj_treesh: { id: 0x029e, index: '0031', readable: 'Object - Tree (Conifer)', category: 'rels', },
  d_a_obj_twGate: { id: 0x029f, index: '0051', readable: 'Object - Twilight Gate', category: 'rels', },
  d_a_obj_udoor: { id: 0x02a0, index: '0129', readable: 'Object - Stable Door', category: 'rels', },
  d_a_obj_usaku: { id: 0x02a1, index: '012a', readable: 'Object - Horse Fence', category: 'rels', },
  d_a_obj_vground: { id: 0x02a2, index: '00e2', readable: 'Object - Volcano Ground', category: 'rels', },
  d_a_obj_volcball: { id: 0x02a3, index: '00e0', readable: 'Object - Volcano Ball', category: 'rels', },
  d_a_obj_volcbom: { id: 0x02a4, index: '00e1', readable: 'Object - Volcano Bom', category: 'rels', },
  d_a_obj_warp_kbrg: { id: 0x02a5, index: '00da', readable: 'Object - Warp - K Bridge', category: 'rels', },
  d_a_obj_warp_obrg: { id: 0x02a6, index: '00db', readable: 'Object - Warp - O Bridge', category: 'rels', },
  d_a_obj_waterGate: { id: 0x02a7, index: '0048', readable: 'Object - Water Gate', category: 'rels', },
  d_a_obj_waterPillar: { id: 0x02a8, index: '0044', readable: 'Object - Water Pillar', category: 'rels', },
  d_a_obj_waterfall: { id: 0x02a9, index: '0177', readable: 'Object - Waterfall', category: 'rels', },
  d_a_obj_wchain: { id: 0x02aa, index: '0159', readable: 'Object - W Chain', category: 'rels', },
  d_a_obj_wdStick: { id: 0x02ab, index: '0165', readable: 'Object - Wooden Stick', category: 'rels', },
  d_a_obj_web0: { id: 0x02ac, index: '0028', readable: 'Object - Web 0', category: 'rels', },
  d_a_obj_web1: { id: 0x02ad, index: '0029', readable: 'Object - Web 1', category: 'rels', },
  d_a_obj_well_cover: { id: 0x02ae, index: '0086', readable: 'Object - Well - Cover', category: 'rels', },
  d_a_obj_wflag: { id: 0x02af, index: '0119', readable: 'Object - Wild Boar Flag', category: 'rels', },
  d_a_obj_wind_stone: { id: 0x02b0, index: '018a', readable: 'Object - Wind - Stone', category: 'rels', },
  d_a_obj_window: { id: 0x02b1, index: '0078', readable: 'Object - Window', category: 'rels', },
  d_a_obj_wood_pendulum: { id: 0x02b2, index: '0164', readable: 'Object - Wood - Pendulum', category: 'rels', },
  d_a_obj_wood_statue: { id: 0x02b3, index: '0185', readable: 'Object - Wood - Statue', category: 'rels', },
  d_a_obj_wsword: { id: 0x02b4, index: '0170', readable: 'Object - Wooden Sword', category: 'rels', },
  d_a_obj_yel_bag: { id: 0x02b5, index: '02f7', readable: 'Object - Ilia - Bag', category: 'rels', },
  d_a_obj_ystone: { id: 0x02b6, index: '02f2', readable: 'Object - Twilight Stone', category: 'rels', },
  d_a_obj_zcloth: { id: 0x02b7, index: '0178', readable: 'Object - Zora Cloth', category: 'rels', },
  d_a_obj_zdoor: { id: 0x02b8, index: '0032', readable: 'Object - Zelda Door', category: 'rels', },
  d_a_obj_zrTurara: { id: 0x02b9, index: '00b6', readable: 'Object - Zora Icicle', category: 'rels', },
  d_a_obj_zrTuraraRock: { id: 0x02ba, index: '0188', readable: 'Object - Zora Icicle Rock', category: 'rels', },
  d_a_obj_zraMark: { id: 0x02bb, index: '0285', readable: 'Object - Zora (Adult) Mark', category: 'rels', },
  d_a_obj_zra_freeze: { id: 0x02bc, index: '0282', readable: 'Object - Zora (Adult) - Freeze', category: 'rels', },
  d_a_obj_zra_rock: { id: 0x02bd, index: '0088', readable: 'Object - Zora (Adult) - Rock', category: 'rels', },
  d_a_passer_mng: { id: 0x02be, index: '028e', readable: 'Passer - Man (General)', category: 'rels', },
  d_a_peru: { id: 0x02bf, index: '0107', readable: 'Peru', category: 'rels', notes: 'Louise', },
  d_a_ppolamp: { id: 0x02c0, index: '0102', readable: 'P Poe Lamp', category: 'rels', },
  d_a_skip_2D: { id: 0x02c1, index: '005b', readable: 'Skip - 2D', category: 'rels', },
  d_a_startAndGoal: { id: 0x02c2, index: '0306', readable: 'Start And Goal', category: 'rels', },
  d_a_swBall: { id: 0x02c3, index: '017e', readable: 'Switch (Ball)', category: 'rels', },
  d_a_swLBall: { id: 0x02c4, index: '017d', readable: 'Switch (L Ball)', category: 'rels', },
  d_a_swTime: { id: 0x02c5, index: '01a1', readable: 'Switch (Time)', category: 'rels', },
  d_a_tag_Lv6Gate: { id: 0x02c6, index: '02c9', readable: 'Tag - Level 6 Gate', category: 'rels', },
  d_a_tag_Lv7Gate: { id: 0x02c7, index: '02ca', readable: 'Tag - Level 7 Gate', category: 'rels', },
  d_a_tag_Lv8Gate: { id: 0x02c8, index: '02cb', readable: 'Tag - Level 8 Gate', category: 'rels', },
  d_a_tag_TWgate: { id: 0x02c9, index: '02c8', readable: 'Tag - Twilight Gate', category: 'rels', },
  d_a_tag_arena: { id: 0x02ca, index: '024c', readable: 'Tag - Arena', category: 'rels', },
  d_a_tag_assistance: { id: 0x02cb, index: '02cd', readable: 'Tag - Assistance', category: 'rels', },
  d_a_tag_bottle_item: { id: 0x02cc, index: '0123', readable: 'Tag - Bottle - Item', category: '', },
  d_a_tag_chgrestart: { id: 0x02cd, index: '022e', readable: 'Tag - Change Restart', category: 'rels', },
  d_a_tag_csw: { id: 0x02ce, index: '0222', readable: 'Tag - Copy Switch', category: 'rels', },
  d_a_tag_escape: { id: 0x02cf, index: '028a', readable: 'Tag - Escape', category: 'rels', },
  d_a_tag_firewall: { id: 0x02d0, index: '01f7', readable: 'Tag - Fire Wall', category: 'rels', },
  d_a_tag_gra: { id: 0x02d1, index: '0022', readable: 'Tag - Goron A', category: 'rels', },
  d_a_tag_guard: { id: 0x02d2, index: '0296', readable: 'Tag - Guard', category: 'rels', },
  d_a_tag_instruction: { id: 0x02d3, index: '024d', readable: 'Tag - Instruction', category: 'rels', },
  d_a_tag_kago_fall: { id: 0x02d4, index: '0181', readable: 'Tag - Basket - Fall', category: 'rels', },
  d_a_tag_lightball: { id: 0x02d5, index: '017c', readable: 'Tag - Light Ball', category: 'rels', },
  d_a_tag_lv5soup: { id: 0x02d6, index: '0124', readable: 'Tag - Level 5 Soup', category: '', },
  d_a_tag_lv6CstaSw: { id: 0x02d7, index: '0191', readable: 'Tag - Level 6 Copy Statue Switch', category: 'rels', },
  d_a_tag_mmsg: { id: 0x02d8, index: '02c2', readable: 'Tag - Midna Message', category: 'rels', },
  d_a_tag_mwait: { id: 0x02d9, index: '02c3', readable: 'Tag - Midna Wait', category: 'rels', },
  d_a_tag_myna2: { id: 0x02da, index: '0287', readable: 'Tag - Myna 2', category: 'rels', },
  d_a_tag_myna_light: { id: 0x02db, index: '0125', readable: 'Tag - Myna - Light', category: 'rels', },
  d_a_tag_pachi: { id: 0x02dc, index: '0272', readable: 'Tag - Slingshot', category: 'rels', },
  d_a_tag_poFire: { id: 0x02dd, index: '017a', readable: 'Tag - Poe Fire', category: 'rels', },
  d_a_tag_qs: { id: 0x02de, index: '0223', readable: 'Tag - Quicksand', category: 'rels', },
  d_a_tag_ret_room: { id: 0x02df, index: '0189', readable: 'Tag - Return - Room', category: 'rels', },
  d_a_tag_river_back: { id: 0x02e0, index: '0180', readable: 'Tag - River - Back', category: 'rels', },
  d_a_tag_rmbit_sw: { id: 0x02e1, index: '01ab', readable: 'Tag - Room Bit - Switch', category: 'rels', },
  d_a_tag_schedule: { id: 0x02e2, index: '0289', readable: 'Tag - Schedule', category: 'rels', },
  d_a_tag_setBall: { id: 0x02e3, index: '019f', readable: 'Tag - Set Ball', category: 'rels', },
  d_a_tag_setrestart: { id: 0x02e4, index: '022f', readable: 'Tag - Set Restart', category: 'rels', },
  d_a_tag_shop_camera: { id: 0x02e5, index: '0126', readable: 'Tag - Shop - Camera', category: 'rels', },
  d_a_tag_shop_item: { id: 0x02e6, index: '0127', readable: 'Tag - Shop - Item', category: 'rels', },
  d_a_tag_smk_emt: { id: 0x02e7, index: '01a0', readable: 'Tag - Smoke - Emit', category: 'rels', },
  d_a_tag_spinner: { id: 0x02e8, index: '00c3', readable: 'Tag - Spinner', category: 'rels', },
  d_a_tag_sppath: { id: 0x02e9, index: '02c6', readable: 'Tag - Spinner Path', category: 'rels', },
  d_a_tag_ss_drink: { id: 0x02ea, index: '0122', readable: 'Tag - SS - Drink', category: 'rels', },
  d_a_tag_stream: { id: 0x02eb, index: '02c5', readable: 'Tag - Stream', category: 'rels', },
  d_a_tag_theB_hint: { id: 0x02ec, index: '02cc', readable: 'Tag - Thelma B - Hint', category: 'rels', },
  d_a_tag_wara_howl: { id: 0x02ed, index: '018b', readable: 'Tag - Wara - Howl', category: 'rels', },
  d_a_tag_watchge: { id: 0x02ee, index: '01f3', readable: 'Tag - Watch Guay', category: 'rels', },
  d_a_tag_waterfall: { id: 0x02ef, index: '01f8', readable: 'Tag - Waterfall', category: 'rels', },
  d_a_tag_wljump: { id: 0x02f0, index: '02c7', readable: 'Tag - Wolf Link Jump', category: 'rels', },
  d_a_tag_yami: { id: 0x02f1, index: '0023', readable: 'Tag - Twilight', category: 'rels', },
  d_a_talk: { id: 0x02f2, index: '02bd', readable: 'Talk', category: 'rels', },
  d_a_tboxSw: { id: 0x02f3, index: '016e', readable: 'Treasure Chest Switch', category: 'rels', },
  d_a_title: { id: 0x02f4, index: '02e1', readable: 'Title', category: 'rels', },
  d_a_warp_bug: { id: 0x02f5, index: '0156', readable: 'Warp - Bug', category: 'rels', },
};

/**
 * Searches list of RELs given a REL identifier which may be a hex id, REL name,
 * or a REL name approximation. Returns a list of REL data which matches the
 * given identifier. If the returned list is length 0, no REL was found. If the
 * returned list is length greater than 1, the returned list contains RELs which
 * the user might have been looking for based on the identifier. If the returned
 * list is length 1, a match was found for the REL identifier.
 *
 * @param {string} relId User-provided REL identifier
 * @returns {array} List of data for possible RELs based on identifier
 */
function findRels(relId) {
  if (typeof relId !== 'string') {
    throw new Error(`Invalid REL name '${relId}'`);
  }

  const relIdMatch = relId.match(/^(0x)?([0-9a-f]+)$/i);

  if (relIdMatch && (relIdMatch[1] || /\d/.test(relIdMatch[2]))) {
    const numValue = parseInt(relId, 16);
    const keys = Object.keys(relsMap);
    const len = keys.length;
    for (let i = 0; i < len; i++) {
      const name = keys[i];
      if (relsMap[name].id === numValue) {
        return [{ ...relsMap[name], name }];
      }
    }
    throw new RecognizedError(`Invalid REL id '${relId}'.`);
  }

  if (/^d_a_/.test(relId) && relsMap[relId]) {
    return [{ ...relsMap[relId], name: relId }];
  }

  const valWithPrefix = 'd_a_' + relId;
  if (relsMap[valWithPrefix]) {
    return [{ ...relsMap[valWithPrefix], name: valWithPrefix }];
  }

  const fuse = new Fuse(Object.keys(relsMap), {
    minMatchCharLength: 3,
  });

  const results = fuse.search(relId);

  let maxSuggestions = results.length > 5 ? 5 : results.length;

  if (relId.length >= 4) {
    const origMaxSuggestions = maxSuggestions;
    maxSuggestions = 0;
    for (let i = 0; i < results.length; i++) {
      if (results[i].item.indexOf(relId) >= 0) {
        maxSuggestions++;
      } else {
        break;
      }
    }

    if (maxSuggestions === 0) {
      maxSuggestions = origMaxSuggestions;
    }
  }

  return results.slice(0, maxSuggestions).map((resultsObj) => {
    const name = resultsObj.item;
    return { ...relsMap[name], name };
  });
}

module.exports = findRels;
